# Generated by Django 5.0.4 on 2024-10-20 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avito_account', '0009_sendingcampaign_auto_generated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Уникальный номер')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('canceled', 'Отменен'), ('waiting_for_capture', 'Ожидание списания'), ('succeeded', 'Оплачен')], default='pending', max_length=30, verbose_name='Статус платежа')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Сумма к списанию')),
                ('income_amount', models.FloatField(blank=True, null=True, verbose_name='Сумма получена')),
                ('balance_tokens', models.IntegerField(default=0, verbose_name='Токенов к зачислению')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Метод оплаты')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Cоздан платёж')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Списана сумма')),
                ('test', models.BooleanField(default=False, verbose_name='Тест')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('confirmation_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка для оплаты')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание платежа')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
            ],
            options={
                'verbose_name': 'Пополнение',
                'verbose_name_plural': 'Пополнения',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профиль',
            },
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('incoming', 'Пополнение'), ('outgoing', 'Списание')], max_length=30, verbose_name='Тип действия')),
                ('amount_tokens', models.FloatField(default=0, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avito_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avito_account.avitoaccount')),
                ('sending_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avito_account.sendingreport')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.userprofile')),
            ],
            options={
                'verbose_name': 'Операция с балансом',
                'verbose_name_plural': 'Операции с балансом',
            },
        ),
    ]
