# Generated by Django 5.0.4 on 2024-10-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_order_id_payment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('succeeded', 'Оплачен'), ('canceled', 'Отменен'), ('pending', 'Ожидание'), ('waiting_for_capture', 'Ожидание списания')], default='pending', max_length=20),
        ),
    ]
