# Generated by Django 5.0.4 on 2024-10-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='uuid',
            field=models.CharField(default=None, editable=False, max_length=36),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('canceled', 'Отменен'), ('waiting_for_capture', 'Ожидание списания'), ('succeeded', 'Оплачен')], default='pending', max_length=20),
        ),
    ]
