# Generated by Django 5.0.4 on 2024-10-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_uuid_alter_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платёж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
