# Generated by Django 5.0.4 on 2024-10-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('payment.pending', 'Ожидание'), ('payment.canceled', 'Отменен'), ('payment.waiting_for_capture', 'Ожидание списания'), ('payment.succeeded', 'Оплачен')], default='payment.pending', max_length=30),
        ),
    ]
