# Generated by Django 5.0.4 on 2024-10-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
