# Generated by Django 5.0.4 on 2024-10-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payment_income_amount_payment_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('canceled', 'Отменен'), ('waiting_for_capture', 'Ожидание списания'), ('succeeded', 'Оплачен')], default='pending', max_length=30),
        ),
    ]
