# Generated by Django 5.0.4 on 2024-10-10 03:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма списана'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='confirmation_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка для оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Воздан платёж'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='RUB', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='income_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма получена'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('canceled', 'Отменен'), ('waiting_for_capture', 'Ожидание списания'), ('succeeded', 'Оплачен')], default='pending', max_length=30, verbose_name='Статус платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='test',
            field=models.BooleanField(default=False, verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Списана сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Уникальный номер'),
        ),
    ]
