# Generated by Django 5.0.4 on 2024-10-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_payment_amount_alter_payment_confirmation_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Воздан платёж'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Списана сумма'),
        ),
    ]
