# Generated by Django 5.0.4 on 2024-10-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_payment_created_at_alter_payment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Cоздан платёж'),
        ),
    ]
