# Generated by Django 5.0.4 on 2024-10-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_payment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма к списанию'),
        ),
    ]
