# Generated by Django 5.0.4 on 2024-10-10 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
