# Generated by Django 5.0.4 on 2024-10-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
