# Generated by Django 5.0.4 on 2024-10-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_alter_userprofile_options_payment_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
