# Generated by Django 5.0.4 on 2024-10-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_remove_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='balance_tokens',
            field=models.IntegerField(default=0, verbose_name='Токенов к зачислению'),
        ),
    ]
