# Generated by Django 5.0.4 on 2024-10-18 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0011_alter_sendingcampaign_test_from_prod'),
        ('payments', '0021_payment_balance_tokens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Пополнение', 'verbose_name_plural': 'Пополнения'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профиль'},
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('incoming', 'Пополнение'), ('outgoing', 'Списание')], max_length=30, verbose_name='Тип действия')),
                ('amount_tokens', models.FloatField(default=0, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito_account.avitoaccount')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('sending_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito_account.sendingreport')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.userprofile')),
            ],
        ),
    ]
