# Generated by Django 5.0.4 on 2024-10-18 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0011_alter_sendingcampaign_test_from_prod'),
        ('payments', '0022_alter_payment_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehistory',
            name='avito_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avito_account.avitoaccount'),
        ),
        migrations.AlterField(
            model_name='balancehistory',
            name='sending_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avito_account.sendingreport'),
        ),
    ]
