# Generated by Django 5.0.4 on 2024-10-18 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_alter_balancehistory_avito_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehistory',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.userprofile'),
        ),
    ]
