# Generated by Django 5.0.4 on 2024-10-18 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_alter_balancehistory_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancehistory',
            options={'verbose_name': 'Операция с балансом', 'verbose_name_plural': 'Операции с балансом'},
        ),
        migrations.AlterField(
            model_name='balancehistory',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment'),
        ),
    ]
