# Generated by Django 5.0.4 on 2025-02-27 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
                ('tokens_completion', models.IntegerField(default=0, verbose_name='Токены на вычисления')),
                ('tokens_prompt', models.IntegerField(default=0, verbose_name='Токены на контекст')),
                ('address', models.TextField(blank=True, default=None, null=True, verbose_name='Адрес клиента')),
                ('mobile', models.TextField(blank=True, default=None, null=True, verbose_name='Мобильный номер')),
                ('whatsapp', models.TextField(blank=True, default=None, null=True, verbose_name='Вацап')),
                ('telegram', models.TextField(blank=True, default=None, null=True, verbose_name='Телеграм')),
                ('email', models.TextField(blank=True, default=None, null=True, verbose_name='Емайл')),
                ('summary_sanded', models.BooleanField(default=False, verbose_name='Сводка была отправлена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_id', models.CharField(max_length=255, verbose_name='Идентификатор чата')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING_DATA', 'Preparing Data'), ('ANSWER_GENERATION', 'Answer Generation'), ('ANSWER_SENDING', 'Answer Sending'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], default='PENDING', verbose_name='Статус')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Задача чат-бота',
                'verbose_name_plural': 'Задачи чат-ботов',
            },
        ),
    ]
