# Generated by Django 5.0.4 on 2024-04-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
