# Generated by Django 5.0.4 on 2024-04-29 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='amount_bonus',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='amount_rub',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='amount_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='avito_account.servicetype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='avito_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='avito_account.avitoaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
