# Generated by Django 5.0.4 on 2024-09-04 08:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0002_analyticschema_avitoaccount_analytic_schema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_start', models.TimeField(default=datetime.time(10, 0), verbose_name='Начало работы (Пн-Пт)')),
                ('weekday_end', models.TimeField(default=datetime.time(18, 0), verbose_name='Окончание работы (Пн-Пт)')),
                ('saturday_is_day_off', models.BooleanField(default=True, verbose_name='Суббота - выходной?')),
                ('saturday_start', models.TimeField(default=datetime.time(10, 0), verbose_name='Суббота - начало работы')),
                ('saturday_end', models.TimeField(default=datetime.time(16, 0), verbose_name='Суббота - окончание работы')),
                ('sunday_is_day_off', models.BooleanField(default=True, verbose_name='Воскресенье - выходной?')),
                ('sunday_start', models.TimeField(default=datetime.time(10, 0), verbose_name='Воскресенье - начало работы')),
                ('sunday_end', models.TimeField(default=datetime.time(16, 0), verbose_name='Воскресенье - окончание работы')),
                ('avito_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='avito_account.avitoaccount')),
            ],
            options={
                'verbose_name': 'Рабочий график (время Московское)',
                'verbose_name_plural': 'Рабочие графики',
            },
        ),
    ]
