# Generated by Django 5.0.4 on 2024-09-14 05:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0003_workschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticschema',
            options={'verbose_name': 'Схема аналитики', 'verbose_name_plural': 'Схемы аналитики'},
        ),
        migrations.AlterModelOptions(
            name='avitoaccount',
            options={'verbose_name': 'Авито аккаунт', 'verbose_name_plural': 'Авито аккаунты'},
        ),
        migrations.AlterModelOptions(
            name='criterion',
            options={'verbose_name': 'Критерий оценки', 'verbose_name_plural': 'Критерии оценки'},
        ),
        migrations.CreateModel(
            name='SendingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('test_from_prod', models.BooleanField(default=False)),
                ('sending_type', models.CharField(choices=[('PDF', 'PDF'), ('TXT', 'Text')], default='PDF', max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accounts_presented_count', models.IntegerField(default=0)),
                ('accounts_presented', models.ManyToManyField(blank=True, related_name='campaigns_presented', to='avito_account.avitoaccount')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='SendingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito_account.avitoaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='avito_account.sendingcampaign')),
            ],
            options={
                'verbose_name': 'Отчёт о рассылке',
                'verbose_name_plural': 'отчёты о рассылках',
            },
        ),
    ]
