# Generated by Django 5.0.4 on 2024-04-29 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0003_operation_amount_bonus_operation_amount_rub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avito_account.item'),
        ),
    ]
