# Generated by Django 5.0.4 on 2024-04-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0004_alter_operation_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='service_id',
            field=models.IntegerField(null=True),
        ),
    ]
