# Generated by Django 5.0.4 on 2024-09-19 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0005_remove_avitoaccount_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avitoaccount',
            name='analytic_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avito_account.analyticschema'),
        ),
    ]
