# Generated by Django 5.0.4 on 2024-04-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0005_servicetype_service_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operation',
            unique_together={('updated_at', 'name')},
        ),
    ]
