# Generated by Django 5.0.4 on 2024-09-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0006_alter_avitoaccount_analytic_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingreport',
            name='tokens_completion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sendingreport',
            name='tokens_prompt',
            field=models.IntegerField(default=0),
        ),
    ]
