# Generated by Django 5.0.4 on 2024-04-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0006_alter_operation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
