# Generated by Django 5.0.4 on 2024-09-26 10:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0007_sendingreport_tokens_completion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticschema',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='analyticschema',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='analyticschema',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название схемы'),
        ),
        migrations.AlterField(
            model_name='avitoaccount',
            name='access_token',
            field=models.CharField(max_length=255, null=True, verbose_name='Токен доступа'),
        ),
        migrations.AlterField(
            model_name='avitoaccount',
            name='analytic_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avito_account.analyticschema', verbose_name='Схема аналитики'),
        ),
        migrations.AlterField(
            model_name='avitoaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='avitoaccount',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='avitoaccount',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название аккаунта'),
        ),
        migrations.AlterField(
            model_name='avitoaccount',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='avitoaccount',
            name='profile_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка на профиль'),
        ),
        migrations.AlterField(
            model_name='avitoaccount',
            name='refresh_token',
            field=models.CharField(max_length=255, null=True, verbose_name='Токен обновления'),
        ),
        migrations.AlterField(
            model_name='avitoaccount',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телеграм ID'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='name',
            field=models.CharField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='avito_account.analyticschema', verbose_name='Схема аналитики'),
        ),
        migrations.AlterField(
            model_name='sendingcampaign',
            name='accounts_presented',
            field=models.ManyToManyField(blank=True, related_name='campaigns_presented', to='avito_account.avitoaccount', verbose_name='Аккаунты к анализу'),
        ),
        migrations.AlterField(
            model_name='sendingcampaign',
            name='accounts_presented_count',
            field=models.IntegerField(default=0, verbose_name='Аккаунтов к анализу'),
        ),
        migrations.AlterField(
            model_name='sendingcampaign',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='sendingcampaign',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название рассылки'),
        ),
        migrations.AlterField(
            model_name='sendingcampaign',
            name='sending_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('TXT', 'Text')], default='PDF', max_length=3, verbose_name='Тип рассылки'),
        ),
        migrations.AlterField(
            model_name='sendingcampaign',
            name='test_from_prod',
            field=models.BooleanField(default=False, verbose_name='Тестирование с прода'),
        ),
        migrations.AlterField(
            model_name='sendingreport',
            name='avito_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito_account.avitoaccount', verbose_name='Авито аккаунт'),
        ),
        migrations.AlterField(
            model_name='sendingreport',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='avito_account.sendingcampaign', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='sendingreport',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сообщение ошибки'),
        ),
        migrations.AlterField(
            model_name='sendingreport',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка к пдф отчёту'),
        ),
        migrations.AlterField(
            model_name='sendingreport',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Успешно'),
        ),
        migrations.AlterField(
            model_name='sendingreport',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='sendingreport',
            name='tokens_completion',
            field=models.IntegerField(default=0, verbose_name='Токены на вычисления'),
        ),
        migrations.AlterField(
            model_name='sendingreport',
            name='tokens_prompt',
            field=models.IntegerField(default=0, verbose_name='Токены на контекст'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='avito_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='avito_account.avitoaccount', verbose_name='Авито аккаунт'),
        ),
        migrations.CreateModel(
            name='ExcludedItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID объявления')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название объявления')),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_items', to='avito_account.avitoaccount', verbose_name='Аккаунт Avito')),
            ],
            options={
                'verbose_name': 'Объявление исключённое',
                'verbose_name_plural': 'Объявления исключённые',
                'unique_together': {('avito_account', 'id')},
            },
        ),
    ]
