# Generated by Django 5.0.4 on 2024-04-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0007_alter_operation_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operation',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
