# Generated by Django 5.0.4 on 2024-05-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0008_delete_operation_delete_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitoaccount',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
