# Generated by Django 5.0.4 on 2024-10-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0008_alter_analyticschema_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingreport',
            name='balance_decrease',
            field=models.IntegerField(default=0, verbose_name='К списанию с баланса'),
        ),
    ]
