# Generated by Django 5.0.4 on 2024-10-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0009_sendingreport_balance_decrease'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingcampaign',
            name='auto_generated',
            field=models.BooleanField(default=False, verbose_name='Автоматически'),
        ),
    ]
