# Generated by Django 5.0.4 on 2024-11-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0009_sendingcampaign_auto_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitoaccount',
            name='balance_alerting',
            field=models.BooleanField(default=True, verbose_name='Уведомления о заканчивающемся балансе'),
        ),
    ]
