# Generated by Django 5.0.4 on 2025-06-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0010_avitoaccount_balance_alerting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingreport',
            name='avito_account_name',
            field=models.CharField(default='blank', max_length=255, verbose_name='Название Avito-аккаунт'),
            preserve_default=False,
        ),
    ]
