# Generated by Django 5.0.4 on 2024-05-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0010_alter_avitoaccount_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avitoaccount',
            name='refresh_token',
        ),
    ]
