# Generated by Django 5.0.4 on 2024-10-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0010_sendingcampaign_auto_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingcampaign',
            name='test_from_prod',
            field=models.BooleanField(default=False, verbose_name='Тест'),
        ),
    ]
