# Generated by Django 5.0.4 on 2024-05-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0011_remove_avitoaccount_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitoaccount',
            name='refresh_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
