# Generated by Django 5.0.4 on 2025-08-31 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0011_sendingreport_avito_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoItem',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор в системе Авито')),
                ('url', models.CharField(db_index=True, max_length=255, null=True, verbose_name='URL')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('status', models.CharField(verbose_name='Статус')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito_account.avitoaccount', verbose_name='Авито-аккаупт')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
