# Generated by Django 5.0.4 on 2025-09-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0012_avitoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitoitem',
            name='relative_link',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Относительная ссылка'),
        ),
        migrations.AlterField(
            model_name='avitoitem',
            name='url',
            field=models.CharField(max_length=255, null=True, verbose_name='URL'),
        ),
    ]
