# Generated by Django 5.0.4 on 2025-09-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0013_avitoitem_relative_link_alter_avitoitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitoaccount',
            name='weekly_pdf_report',
            field=models.BooleanField(default=True, verbose_name='Еженедельный PDF отчет'),
        ),
        migrations.AddField(
            model_name='avitoaccount',
            name='weekly_text_report',
            field=models.BooleanField(default=True, verbose_name='Еженедельный текстовый отчет'),
        ),
    ]
