# Generated by Django 5.0.4 on 2024-04-30 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avito_account', '0008_delete_operation_delete_servicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, null=True)),
                ('service_type', models.CharField(max_length=255, null=True)),
                ('service_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_bonus', models.IntegerField()),
                ('amount_rub', models.IntegerField()),
                ('amount_total', models.IntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avito_account.item')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversion.servicetype')),
            ],
            options={
                'unique_together': {('updated_at', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('uniq_contacts', models.IntegerField()),
                ('uniq_favorites', models.IntegerField()),
                ('uniq_views', models.IntegerField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avito_account.item')),
            ],
            options={
                'unique_together': {('item', 'date')},
            },
        ),
    ]
