# Generated by Django 5.0.4 on 2024-08-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statistic',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='item',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
