# Generated by Django 5.0.4 on 2024-05-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_conversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversion',
        ),
    ]
