version: "3.0"

services:
  db:
    container_name: "avitostata_db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "${DB_PORT}:5432"
    networks:
      - custom
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: "redis"
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - custom
    volumes:
      - redis_data:/data

  django:
    build:
      context: .
    depends_on:
      - db
      - redis
    command: "python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    networks:
      - custom
    env_file: ".env"
    volumes:
      - .:/avitostat

  celery-worker:
    build:
      context: .
    depends_on:
      - db
      - redis
    command: "celery -A base worker -l info --pool solo"
    restart: always
    networks:
      - custom
    env_file: ".env"

  celery-beat:
    build:
      context: .
    depends_on:
      - db
      - redis
    command: "celery -A base beat -l info"
    restart: always
    networks:
      - custom
    env_file: ".env"

networks:
  custom:
    driver: bridge

volumes:
  pgdata:
  redis_data:
