--
-- PostgreSQL database dump
--

-- Dumped from database version 14.12 (Ubuntu 14.12-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.12 (Ubuntu 14.12-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO myuser;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO myuser;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO myuser;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO myuser;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO myuser;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO myuser;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avito_account_analyticschema; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.avito_account_analyticschema (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    name character varying(32) NOT NULL,
    created_by_id integer
);


ALTER TABLE public.avito_account_analyticschema OWNER TO myuser;

--
-- Name: avito_account_analyticschema_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.avito_account_analyticschema ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.avito_account_analyticschema_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avito_account_avitoaccount; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.avito_account_avitoaccount (
    id bigint NOT NULL,
    name character varying(255),
    phone character varying(255),
    profile_url character varying(255),
    access_token character varying(255),
    company_id integer,
    telegram_id character varying(255),
    refresh_token character varying(255),
    analytic_schema_id bigint
);


ALTER TABLE public.avito_account_avitoaccount OWNER TO myuser;

--
-- Name: avito_account_avitoaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.avito_account_avitoaccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.avito_account_avitoaccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avito_account_criterion; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.avito_account_criterion (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    name character varying NOT NULL,
    created_by_id integer,
    schema_id bigint NOT NULL
);


ALTER TABLE public.avito_account_criterion OWNER TO myuser;

--
-- Name: avito_account_criterion_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.avito_account_criterion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.avito_account_criterion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO myuser;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO myuser;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO myuser;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO myuser;

--
-- Name: jet_bookmark; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.jet_bookmark (
    id bigint NOT NULL,
    url character varying(200) NOT NULL,
    title character varying(255) NOT NULL,
    user_id integer,
    date_add timestamp with time zone NOT NULL
);


ALTER TABLE public.jet_bookmark OWNER TO myuser;

--
-- Name: jet_bookmark_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.jet_bookmark ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jet_bookmark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jet_pinnedapplication; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.jet_pinnedapplication (
    id bigint NOT NULL,
    app_label character varying(255) NOT NULL,
    user_id integer,
    date_add timestamp with time zone NOT NULL
);


ALTER TABLE public.jet_pinnedapplication OWNER TO myuser;

--
-- Name: jet_pinnedapplication_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.jet_pinnedapplication ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jet_pinnedapplication_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add avito account	7	add_avitoaccount
26	Can change avito account	7	change_avitoaccount
27	Can delete avito account	7	delete_avitoaccount
28	Can view avito account	7	view_avitoaccount
29	Can add item	8	add_item
30	Can change item	8	change_item
31	Can delete item	8	delete_item
32	Can view item	8	view_item
33	Can add service type	9	add_servicetype
34	Can change service type	9	change_servicetype
35	Can delete service type	9	delete_servicetype
36	Can view service type	9	view_servicetype
37	Can add operation	10	add_operation
38	Can change operation	10	change_operation
39	Can delete operation	10	delete_operation
40	Can view operation	10	view_operation
41	Can add statistic	11	add_statistic
42	Can change statistic	11	change_statistic
43	Can delete statistic	11	delete_statistic
44	Can view statistic	11	view_statistic
45	Can add pinned application	12	add_pinnedapplication
46	Can change pinned application	12	change_pinnedapplication
47	Can delete pinned application	12	delete_pinnedapplication
48	Can view pinned application	12	view_pinnedapplication
49	Can add bookmark	13	add_bookmark
50	Can change bookmark	13	change_bookmark
51	Can delete bookmark	13	delete_bookmark
52	Can view bookmark	13	view_bookmark
53	Can add analytic schema	14	add_analyticschema
54	Can change analytic schema	14	change_analyticschema
55	Can delete analytic schema	14	delete_analyticschema
56	Can view analytic schema	14	view_analyticschema
57	Can add criterion	15	add_criterion
58	Can change criterion	15	change_criterion
59	Can delete criterion	15	delete_criterion
60	Can view criterion	15	view_criterion
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
3	pbkdf2_sha256$720000$nD4dn8NxscphQ4cEP42z5B$kBKMM464ffT8DvO1zbgKjjqm/Ps5SCAWE6SghJpsgSw=	2024-06-26 15:25:12.505065+00	f	Georgy				t	t	2024-06-26 07:52:11+00
2	pbkdf2_sha256$720000$e9tF3a9vP8wEGaeJCwuPZT$qpz0iN7kPIoOLGlWaROg0KXOPLEIkBetIWIKnu8pjdo=	2024-06-25 16:52:10+00	f	Rauf				t	t	2024-06-25 11:25:44+00
1	pbkdf2_sha256$720000$gnHHSvWGDz27EGoHvHt4ZA$uIvbDYBeqmJ3YSH1OyoazXEMtV0iL9OJbIm93BbLseI=	2024-08-18 06:07:00.218465+00	t	admin007				t	t	2024-05-19 11:05:38+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
1	2	25
2	2	26
3	2	27
4	2	28
5	3	25
6	3	26
7	3	27
8	3	28
\.


--
-- Data for Name: avito_account_analyticschema; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.avito_account_analyticschema (id, created_at, name, created_by_id) FROM stdin;
\.


--
-- Data for Name: avito_account_avitoaccount; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.avito_account_avitoaccount (id, name, phone, profile_url, access_token, company_id, telegram_id, refresh_token, analytic_schema_id) FROM stdin;
365995534	ShopIhlas	79274067410	https://www.avito.ru/user/151db1f10dcc64d9f5f1b1bfe11d9be5/profile	60J2N2jGSIuiCH4RmxKMMAjTm04Fmv7ruBnxQaQY	1	-1001879342227	zY3pE19jSO23K0Fhwbf4QAq5kLPP8bH4hyKt3TkeN5-0KlB5J-wqVbfkrkjCGubCjNnyeW7ch9pR3tUIXYAt7Bj6KXYkPacxkEjBa3JU2xRj1k7WYSDWVAEBev6ElLsD	\N
370956433	Муссон - Вентиляторы	78007000471	https://www.avito.ru/user/930463e8c03977198daf6dcacbba8b87/profile	PRdlIr8KSS6IfXX6y1ZjFAkVZaW30QRRZtJFQ46_	1	-1002123365387	Q_Bk-Ih-S46Bjzf82lvFwQukdj63ZbBDnKstW2Io7nB2hFu2vVJLuYA5Yj93oaxf5pLQ4QqZ2r2njKxTYOnRuUlFVQcRD7qeEl0WmC9K39n9yFCNb1ZY45Ae4fWxF8ax	\N
375856903	Металлит	79162545454	https://www.avito.ru/user/25ec04b22e092e2c03fa6896e1b4ebaa/profile	EajO2WBFQAqNdcDHU_jIZAgJwTs1dPaicXwgPqLc	1	-1002045627223	rMjLk_hJQpa79E1ZEUDvGg5heAfE0vp3AB0Z1T5I9lUjBVVoyeypWJVJrUb95rmwxRFwprUOwWKf64FSoP6wVtRggwSgfEWYXCPi5WGqcTLyI-uuVGpCYwx3eoKVaaif	\N
162104680	Авитолог на миллион	79675553997	https://www.avito.ru/user/8f188938967601bcc20d2e12449fe3ca/profile	4O5IgiIdSmqGw2UcN17eoQ3zt-_m93EaKstVXBLq	3	-4220952805	QlohIG9PRgyDPnPWB4G3vAgq6_1SvqZUnJYcRI0oRLr6u6t9rrxviUb3K6lfz6v9TXQsCfvW4OcMyPEQE4ObpHgUt-e7Wxl70Z7btSqLa5kz_9xVeZYLx7NTAYcQE3bh	\N
184133522	АПР ТРЕЙД	79274986257	https://www.avito.ru/user/f5977f45f31f269ec0e21f78fe1125a1/profile	B_BZblVYTDatjJVWHgT3aArKDTX_pFWFxc059BsS	1	-1001710724190	xcByiuw2TdapohMD29Ek2QIq-2LYMXVMZAoMq39gSe3PHgQJwMC65zBfvLgOrzrq8mO2JdujJaxM3kNf15wCJh6pkA4KymuQfXYiQOk5b5LHXGAyq4nq9y8BMGM-eEqG	\N
84804440	Техно Hab Str	79920027219	https://www.avito.ru/user/bfebfb1d7de1ce17141ea8f245d767dd/profile	kwKZFwruRju-RLdOJLnuoAswEutiJAEFx7RPQsxo	2	-4235716536	L1olJO53QiS3dSMA28ppBwJFrqrXhKJ1vdbh6XVlucgulkZGFJtdAee_h9rhYdmE4uvvmly26nD7hhHoCMOVHuFxHplmnD571jDzhuSUCjUW6NdGcWdhMCQbhOW4-IiC	\N
60388532	FriendsMasters	79263555596	https://www.avito.ru/user/5ae7b369778bff5f24ed571bf50b6e64/profile	oBbhGJAERmy1sr0OjivE9ghzV1_Hqxcm-pVQvrFs	1	-1001631515577	Oz86kunpTeSHMd4iHmceMA_SUuKRxgisWpJMpfa1NYHRDPz45oceXtyxcdw5VVL42OIg1GSH__3mkVhFMnRzPh3ZLBolYZLBlZUlXtfkn4V4RGiIzbFRBn_wM70aWFPr	\N
174153815	RiverAutoLab	79165624747	https://www.avito.ru/user/6153defb04d406f756ffa7112ebba37e/profile	VROqtXujQrSOdhUug5eeYAanzmDvHDLgKXppPbP1	1	-1001631515577	fm5qPqOZR0GJ8Q3C7_n1rQhpL-o0J3kBJBnPBJlhtQODZ27Z4Do4Ux9kuYyLXfXpJceu9RZTww81l0Skm2wbzAMxqaQuR9eCT5msDbqOKGsf5-CFGisxCNqIszqbeSAV	\N
145213826	Мастер Рауф	79173570175	https://www.avito.ru/user/bfacd971a3a3d3fac034abdd034ebf80/profile	QiPZMPFMQrmmO4NXEYsO2gWm46M71HCPg3b_1Gi8	2	-4221870448	sKqmGzccQ7CKbtFDd6t0RQPofJBh5QSYOeNHJAIrnQ3pVURvxQfUOE9CWyvENgK4LY4F99kl5bsbHzlElA2vhdS6G3WdL8ctXT7T2pBPQtQU2DKIUUC6iGp0_DobqtWl	\N
369782036	BLACK OUD - все для парфюмеров	79274067080	https://www.avito.ru/user/b9bee3efd39c73fe4aa45e76b1dc1b74/profile	AyaXkmRpQkajE3zw8BZERAg9kspI4M_qa3cN22Ft	1	-1001814516816	olLbisINTgmKLVO4H8RgNwJ4ZuUy2-QQrkBcKhbl15baBR8VgiUQMf9IZ1lQaYNxXIVvBCoD7bjRpyIZyAzTnfsMAhByu7p8YdbXm5Wka930u_VuFb_gvruVWXsD8Dcw	\N
203199629	TD Eurostroy - доставка стройматериалов	79600327785	https://www.avito.ru/user/0af970a464be3740d4a2d3ee028ca6da/profile	uW7QNLQ-QJmafz3dVaQU_QHOkwll5DZFXQrWPw7Q	1	-1001993197787	fKy15LPnQbmUWeBOJ9EEOgXB6CABXI5veeCu9IMea6v_3TrKLJWs64Z7P4zEDzV_WTzvGu9YIkEHO0JpOSE1kAImvEpTgPYlV1cXIvd-fEA7V2dJDDS_Cc20QeLm5trL	\N
302256385	Производитель ЭМИЗ и БАЗР	79869151458	https://www.avito.ru/user/e5b3df685bb6599e49b91eb03b72abbe/profile	KqBl9HTTSquJdEE_8HA0sgOKtk9CyZtuuyBnfwoQ	1	-1001660600401	mgaXZ6CSQWiJjdALNgjQSgMkC0NY_umXCGuKsHxR3H0pgcZXxf796BcwlWP8SJvwoD37MZvV7QkSqoyeKF9Lnr9JTvwEXRGrjPx8K19JNq7YyTXrr3I2qI1lkD2gQXJx	\N
357644259	TOKARKA-PRO	79662500035	https://www.avito.ru/user/d925f0e3f7cf63f2173e75d4d5174884/profile	13Zv45OgQLS-aXtun5x1uwfwiOSE058G4S2VsOjC	1	-1002063475776	VvVwKsLGRpyRM9V0EGIeNwRil5KVIX9i7N86y07XVz7whmZFouIAPnwEwoV65BrT6E4jZVNviMnr8l8pSluA_sCdPbIos6cDavBRvb3wMKmqcYzlTa9_mcHNVAGus0ve	\N
\.


--
-- Data for Name: avito_account_criterion; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.avito_account_criterion (id, created_at, name, created_by_id, schema_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2024-05-22 04:02:29.172695+00	203199629	TD Eurostroy - доставка стройматериалов, 203199629	3		7	1
2	2024-06-03 11:52:03.756399+00	145213826	Мастер Рауф, 145213826	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
3	2024-06-03 12:03:02.803381+00	203199629	TD Eurostroy - доставка стройматериалов, 203199629	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
4	2024-06-03 12:05:03.828368+00	145213826	Мастер Рауф, 145213826	2	[]	7	1
5	2024-06-03 12:14:00.422531+00	184133522	АПР ТРЕЙД, 184133522	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
6	2024-06-03 12:14:55.308528+00	145213826	Мастер Рауф, 145213826	3		7	1
7	2024-06-03 14:05:21.114305+00	203199629	TD Eurostroy - доставка стройматериалов, 203199629	3		7	1
8	2024-06-03 14:26:38.860237+00	184133522	АПР ТРЕЙД, 184133522	2	[]	7	1
9	2024-06-03 19:14:39.08531+00	203199629	TD Eurostroy - доставка стройматериалов, 203199629	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
10	2024-06-03 19:20:11.549176+00	84804440	Техно Hab Str, 84804440	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
11	2024-06-05 00:24:45.404572+00	184133522	АПР ТРЕЙД, 184133522	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
12	2024-06-05 00:36:47.411698+00	1	admin	2	[{"changed": {"fields": ["password"]}}]	4	1
13	2024-06-05 00:37:24.496716+00	1	admin007	2	[{"changed": {"fields": ["Username"]}}]	4	1
14	2024-06-05 09:58:12.361072+00	203199629	TD Eurostroy - доставка стройматериалов, 203199629	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
15	2024-06-05 09:58:26.832996+00	84804440	Техно Hab Str, 84804440	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
16	2024-06-05 09:58:35.049824+00	184133522	АПР ТРЕЙД, 184133522	2	[]	7	1
17	2024-06-06 09:53:06.2868+00	357644259	TOKARKA-PRO, 357644259	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
18	2024-06-06 10:02:19.185317+00	84804440	Техно Hab Str, 84804440	3		7	1
19	2024-06-06 10:03:05.281065+00	203199629	TD Eurostroy - доставка стройматериалов, 203199629	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
20	2024-06-06 10:08:02.078857+00	184133522	АПР ТРЕЙД, 184133522	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
21	2024-06-08 11:41:24.535336+00	84804440	Техно Hab Str, 84804440	3		7	1
22	2024-06-19 09:08:27.218146+00	365995534	ShopIhlas, 1001879342227	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
23	2024-06-19 09:10:28.982249+00	365995534	ShopIhlas, -1001879342227	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
24	2024-06-19 09:10:37.106537+00	365995534	ShopIhlas, -1001879342227	2	[]	7	1
25	2024-06-19 09:14:57.687252+00	369782036	BLACK OUD - все для парфюмеров, -1001814516816	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
26	2024-06-19 09:20:38.005446+00	302256385	Производитель ЭМИЗ и БАЗР, -1001660600401	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
27	2024-06-19 09:23:21.306597+00	370956433	Муссон - Вентиляторы, -1002123365387	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
28	2024-06-19 09:25:13.956295+00	375856903	Металлит, -1002045627223	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
29	2024-06-20 16:15:03.952792+00	184133522	АПР ТРЕЙД, -1001710724190	2	[]	7	1
30	2024-06-25 11:25:44.818377+00	2	test1	1	[{"added": {}}]	4	1
31	2024-06-25 11:26:04.112974+00	2	test1	2	[{"changed": {"fields": ["User permissions"]}}]	4	1
32	2024-06-25 11:28:26.002974+00	2	test1	2	[{"changed": {"fields": ["password"]}}]	4	1
33	2024-06-25 11:29:02.501067+00	2	test1	2	[{"changed": {"fields": ["Staff status"]}}]	4	1
34	2024-06-25 14:41:07.548321+00	145213826	Мастер Рауф, None	2	[{"changed": {"fields": ["Company"]}}]	7	1
35	2024-06-25 14:43:24.275972+00	375856903	Металлит, -1002045627223	2	[{"changed": {"fields": ["Company"]}}]	7	1
36	2024-06-25 14:43:36.130258+00	370956433	Муссон - Вентиляторы, -1002123365387	2	[{"changed": {"fields": ["Company"]}}]	7	1
37	2024-06-25 14:43:46.419482+00	369782036	BLACK OUD - все для парфюмеров, -1001814516816	2	[{"changed": {"fields": ["Company"]}}]	7	1
38	2024-06-25 14:43:55.713373+00	365995534	ShopIhlas, -1001879342227	2	[{"changed": {"fields": ["Company"]}}]	7	1
39	2024-06-25 14:48:08.630233+00	357644259	TOKARKA-PRO, -1002063475776	2	[{"changed": {"fields": ["Company"]}}]	7	1
40	2024-06-25 14:48:18.805709+00	302256385	Производитель ЭМИЗ и БАЗР, -1001660600401	2	[{"changed": {"fields": ["Company"]}}]	7	1
41	2024-06-25 14:48:25.861755+00	203199629	TD Eurostroy - доставка стройматериалов, -1001993197787	2	[{"changed": {"fields": ["Company"]}}]	7	1
42	2024-06-25 14:48:32.851226+00	184133522	АПР ТРЕЙД, -1001710724190	2	[{"changed": {"fields": ["Company"]}}]	7	1
43	2024-06-25 17:49:16.901388+00	145213826	Мастер Рауф, None	3		7	1
44	2024-06-26 07:45:58.798301+00	375856903	Металлит, -1002045627223	2	[{"changed": {"fields": ["Company"]}}]	7	1
45	2024-06-26 07:46:51.700372+00	375856903	Металлит, -1002045627223	2	[{"changed": {"fields": ["Company"]}}]	7	1
46	2024-06-26 07:49:16.880643+00	162104680	Авитолог на миллион, None	2	[{"changed": {"fields": ["Company"]}}]	7	2
47	2024-06-26 07:49:37.549812+00	162104680	Авитолог на миллион, None	2	[{"changed": {"fields": ["Company"]}}]	7	2
48	2024-06-26 07:52:11.498814+00	3	Георгий	1	[{"added": {}}]	4	1
49	2024-06-26 07:53:25.545185+00	3	Георгий	2	[{"changed": {"fields": ["Staff status"]}}]	4	1
50	2024-06-26 07:55:49.556355+00	3	Георгий	2	[{"changed": {"fields": ["User permissions"]}}]	4	1
51	2024-06-26 07:56:36.669373+00	162104680	Авитолог на миллион, None	2	[{"changed": {"fields": ["Company"]}}]	7	3
52	2024-06-26 07:56:42.913894+00	162104680	Авитолог на миллион, None	2	[{"changed": {"fields": ["Company"]}}]	7	3
53	2024-06-26 07:57:34.540924+00	1	admin007	2	[{"changed": {"fields": ["password"]}}]	4	1
54	2024-06-26 08:04:25.601178+00	174153815	RiverAutoLab, None	2	[{"changed": {"fields": ["Company"]}}]	7	1
55	2024-06-26 08:05:09.670229+00	174153815	RiverAutoLab, -1001631515577	2	[{"changed": {"fields": ["Telegram id"]}}]	7	1
56	2024-06-26 08:06:46.226523+00	60388532	FriendsMasters, -1001631515577	2	[{"changed": {"fields": ["Company", "Telegram id"]}}]	7	1
57	2024-06-26 08:07:11.499602+00	162104680	Авитолог на миллион, None	2	[{"changed": {"fields": ["Company"]}}]	7	1
58	2024-06-26 09:01:59.301726+00	3	Georgy	2	[{"changed": {"fields": ["Username"]}}]	4	1
59	2024-06-26 15:30:30.424151+00	162104680	Авитолог на миллион, -4220952805	2	[{"changed": {"fields": ["Telegram id"]}}]	7	3
60	2024-07-06 15:23:04.204531+00	145213826	Мастер Рауф, -4221870448	2	[{"changed": {"fields": ["Company", "Telegram id"]}}]	7	1
61	2024-07-11 13:39:30.848414+00	375856903	Металлит, -1002045627223	3		7	1
62	2024-07-11 13:39:30.852836+00	357644259	TOKARKA-PRO, -1002063475776	3		7	1
63	2024-07-11 13:39:30.854032+00	60388532	FriendsMasters, -1001631515577	3		7	1
64	2024-07-12 06:55:53.91907+00	357644259	TOKARKA-PRO, None	3		7	1
65	2024-07-12 07:00:32.688337+00	357644259	TOKARKA-PRO, -1002063475776	2	[{"changed": {"fields": ["Company", "Telegram id"]}}]	7	1
66	2024-07-12 07:03:29.041821+00	375856903	Металлит, -1002045627223	2	[{"changed": {"fields": ["Company", "Telegram id"]}}]	7	1
67	2024-07-12 07:05:09.92648+00	60388532	FriendsMasters, -1001631515577	2	[{"changed": {"fields": ["Company", "Telegram id"]}}]	7	1
68	2024-07-12 07:42:11.412164+00	370956433	Муссон - Вентиляторы, -1002123365387	2	[{"changed": {"fields": ["Access token", "Refresh token"]}}]	7	1
69	2024-07-12 07:42:55.851511+00	145213826	Мастер Рауф, -4221870448	2	[{"changed": {"fields": ["Access token", "Refresh token"]}}]	7	1
70	2024-07-12 09:53:55.892769+00	370956433	Муссон - Вентиляторы, -1002123365387	2	[]	7	1
71	2024-07-12 09:54:28.476348+00	369782036	BLACK OUD - все для парфюмеров, -1001814516816	2	[{"changed": {"fields": ["Access token", "Refresh token"]}}]	7	1
72	2024-07-12 09:54:56.920336+00	365995534	ShopIhlas, -1001879342227	2	[{"changed": {"fields": ["Access token", "Refresh token"]}}]	7	1
73	2024-07-12 09:55:16.179134+00	302256385	Производитель ЭМИЗ и БАЗР, -1001660600401	2	[{"changed": {"fields": ["Access token", "Refresh token"]}}]	7	1
74	2024-07-12 09:55:40.553883+00	203199629	TD Eurostroy - доставка стройматериалов, -1001993197787	2	[{"changed": {"fields": ["Access token", "Refresh token"]}}]	7	1
75	2024-07-12 09:55:59.901469+00	184133522	АПР ТРЕЙД, -1001710724190	2	[{"changed": {"fields": ["Access token", "Refresh token"]}}]	7	1
76	2024-07-12 09:56:25.807104+00	174153815	RiverAutoLab, -1001631515577	2	[{"changed": {"fields": ["Access token", "Refresh token"]}}]	7	1
77	2024-07-12 09:56:44.536872+00	162104680	Авитолог на миллион, -4220952805	2	[{"changed": {"fields": ["Access token", "Refresh token"]}}]	7	1
78	2024-07-12 10:12:26.857212+00	2	Rauf	2	[{"changed": {"fields": ["Username"]}}]	4	1
79	2024-07-12 10:17:14.19366+00	84804440	Техно Hab Str, -4235716536	2	[{"changed": {"fields": ["Company", "Telegram id"]}}]	7	1
80	2024-07-12 10:17:31.172979+00	145213826	Мастер Рауф, -4221870448	2	[{"changed": {"fields": ["Company"]}}]	7	1
81	2024-07-15 05:32:17.096393+00	145213826	Мастер Рауф, -4221870448	3		7	1
82	2024-07-15 05:32:52.125743+00	145213826	Мастер Рауф, -4221870448	2	[{"changed": {"fields": ["Company", "Telegram id"]}}]	7	1
83	2024-07-17 07:12:45.094798+00	145213826	Мастер Рауф, -4221870448	2	[{"changed": {"fields": ["Access token", "Refresh token"]}}]	7	1
84	2024-07-17 11:51:38.005169+00	84804440	Техно Hab Str, -4235716536	2	[]	7	1
85	2024-08-12 14:04:42.005472+00	184133522	АПР ТРЕЙД, -1001710724190	2	[{"changed": {"fields": ["Access token", "Refresh token"]}}]	7	1
86	2024-08-12 14:09:21.257611+00	145213826	Мастер Рауф, -4221870448	2	[{"changed": {"fields": ["Access token", "Refresh token"]}}]	7	1
87	2024-08-18 07:43:11.899598+00	145213826	Мастер Рауф, -4221870448	2	[]	7	1
88	2024-08-18 11:02:55.305055+00	145213826	Мастер Рауф, -4221870448	2	[]	7	1
89	2024-08-18 12:22:41.79693+00	145213826	Мастер Рауф, -4221870448	2	[]	7	1
90	2024-08-18 12:23:09.745023+00	184133522	АПР ТРЕЙД, -1001710724190	2	[]	7	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	avito_account	avitoaccount
8	avito_account	item
9	conversion	servicetype
10	conversion	operation
11	conversion	statistic
12	jet	pinnedapplication
13	jet	bookmark
14	avito_account	analyticschema
15	avito_account	criterion
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2024-05-18 17:12:55.853145+00
2	auth	0001_initial	2024-05-18 17:12:55.90329+00
3	admin	0001_initial	2024-05-18 17:12:55.917317+00
4	admin	0002_logentry_remove_auto_add	2024-05-18 17:12:55.923135+00
5	admin	0003_logentry_add_action_flag_choices	2024-05-18 17:12:55.928803+00
6	contenttypes	0002_remove_content_type_name	2024-05-18 17:12:55.941916+00
7	auth	0002_alter_permission_name_max_length	2024-05-18 17:12:55.947862+00
8	auth	0003_alter_user_email_max_length	2024-05-18 17:12:55.954219+00
9	auth	0004_alter_user_username_opts	2024-05-18 17:12:55.959871+00
10	auth	0005_alter_user_last_login_null	2024-05-18 17:12:55.965583+00
11	auth	0006_require_contenttypes_0002	2024-05-18 17:12:55.966583+00
12	auth	0007_alter_validators_add_error_messages	2024-05-18 17:12:55.971842+00
13	auth	0008_alter_user_username_max_length	2024-05-18 17:12:55.980051+00
14	auth	0009_alter_user_last_name_max_length	2024-05-18 17:12:55.986296+00
15	auth	0010_alter_group_name_max_length	2024-05-18 17:12:55.992992+00
16	auth	0011_update_proxy_permissions	2024-05-18 17:12:55.999862+00
17	auth	0012_alter_user_first_name_max_length	2024-05-18 17:12:56.005718+00
18	avito_account	0001_initial	2024-05-18 17:12:56.039768+00
19	avito_account	0002_alter_item_price	2024-05-18 17:12:56.045202+00
20	avito_account	0003_operation_amount_bonus_operation_amount_rub_and_more	2024-05-18 17:12:56.090523+00
21	avito_account	0004_alter_operation_item	2024-05-18 17:12:56.102202+00
22	avito_account	0005_servicetype_service_id	2024-05-18 17:12:56.105385+00
23	avito_account	0006_alter_operation_unique_together	2024-05-18 17:12:56.110976+00
24	avito_account	0007_alter_operation_updated_at	2024-05-18 17:12:56.114492+00
25	avito_account	0008_delete_operation_delete_servicetype	2024-05-18 17:12:56.11785+00
26	avito_account	0009_avitoaccount_telegram_id	2024-05-18 17:12:56.127498+00
27	avito_account	0010_alter_avitoaccount_company	2024-05-18 17:12:56.135543+00
28	avito_account	0011_remove_avitoaccount_refresh_token	2024-05-18 17:12:56.142054+00
29	avito_account	0012_avitoaccount_refresh_token	2024-05-18 17:12:56.148359+00
30	conversion	0001_initial	2024-05-18 17:12:56.17808+00
31	conversion	0002_conversion	2024-05-18 17:12:56.191759+00
32	conversion	0003_delete_conversion	2024-05-18 17:12:56.193852+00
33	sessions	0001_initial	2024-05-18 17:12:56.20014+00
34	jet	0001_initial	2024-06-03 19:32:21.047391+00
35	jet	0002_delete_userdashboardmodule	2024-06-03 19:32:21.048901+00
36	jet	0003_auto_20201228_1540	2024-06-03 19:32:21.049594+00
37	jet	0004_auto_20201228_1802	2024-06-03 19:32:21.050265+00
38	jet	0001_squashed_0004_auto_20201228_1802	2024-06-03 19:32:21.051752+00
39	jet	0005_alter_bookmark_id_alter_pinnedapplication_id	2024-06-25 15:14:47.223969+00
40	conversion	0002_alter_statistic_unique_together_and_more	2024-08-12 11:30:05.31972+00
41	avito_account	0002_analyticschema_avitoaccount_analytic_schema_and_more	2024-08-12 11:30:05.403413+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
etxfkkbmcq16jyezhgw6xpdg1f2ul8du	.eJxVjDsOwjAQBe_iGln-sg4lfc5g7dobHEC2lE-FuDtYSgHlezOal4i4byXuKy9xzuIitDj9foTpwbWDfMd6azK1ui0zya7Ig65ybJmf18P9CxRcS89yTkErC4MBHox11n3nZDBP6BNYZQACsic6kx8wB2UcACtjNQXSIN4fxXk3CQ:1s8eML:JxDqFk0bYs-vQoZaur7cuDmJYBHCdl5jrs3JPTknUD4	2024-06-02 11:05:45.585216+00
feshnnuupnxix2qbg423r1e3uyhqfuwo	.eJxVjMsOwiAQRf-FtSE8hse4dO83EMqAVA0kpV0Z_12bdKHbe865LxbittawjbyEmdiZSXb63aaYHrntgO6x3TpPva3LPPFd4Qcd_NopPy-H-3dQ46jfOpMHrbLUUWdDljwWiSQMOJUQyFkjS5IEyeqC5IUzCLKgSADCK4rs_QHYgzdW:1s91pj:cqS7l-IZaGnqWJraF1WQuYFL6rnvGI6FmYnjsp4nlzw	2024-06-03 12:09:39.119943+00
tkpa4mm2ry9g7iaqlcgmd69jpx3rqc4g	.eJxVjMsOwiAQRf-FtSE8hse4dO83EMqAVA0kpV0Z_12bdKHbe865LxbittawjbyEmdiZSXb63aaYHrntgO6x3TpPva3LPPFd4Qcd_NopPy-H-3dQ46jfOpMHrbLUUWdDljwWiSQMOJUQyFkjS5IEyeqC5IUzCLKgSADCK4rs_QHYgzdW:1sEDgr:_oFGwErpihWwlXxhqInsNogRu0hQvlPkSaxL0eOBmSY	2024-06-17 19:49:57.248809+00
6emvkuv8tin7obzsoc1bg814c9qktsn8	.eJxVjMsOwiAQRf-FtSE8hse4dO83EMqAVA0kpV0Z_12bdKHbe865LxbittawjbyEmdiZSXb63aaYHrntgO6x3TpPva3LPPFd4Qcd_NopPy-H-3dQ46jfOpMHrbLUUWdDljwWiSQMOJUQyFkjS5IEyeqC5IUzCLKgSADCK4rs_QHYgzdW:1sEE3A:7iccRNZVD5acnIXLqwkwuWKmU-mlVr-J5FNWOxZDt5o	2024-06-17 20:13:00.084103+00
y2mxp34o5lkhmh850ww2c4uo9d37s73m	.eJxVjMsOwiAUBf-FtSFcGii4dO83kPsAqRqalHZl_Hdt0oVuz8ycl0q4rTVtPS9pEnVWoE6_GyE_ctuB3LHdZs1zW5eJ9K7og3Z9nSU_L4f7d1Cx12_NFMCOYxnM4AqGYpg9sYAJNnouJOR8BCTP0QFTAV8QrAvRBPJCWb0_9k04jg:1sEedz:6pdcdXPr1NtHy8_PEwoCwa01HPTZ9eSaPjETK7ipqR0	2024-06-19 00:36:47.430685+00
vbpt3vvefx2348v6lputq2bfehwo0nyn	.eJxVjMsOwiAUBf-FtSFcGii4dO83kPsAqRqalHZl_Hdt0oVuz8ycl0q4rTVtPS9pEnVWoE6_GyE_ctuB3LHdZs1zW5eJ9K7og3Z9nSU_L4f7d1Cx12_NFMCOYxnM4AqGYpg9sYAJNnouJOR8BCTP0QFTAV8QrAvRBPJCWb0_9k04jg:1sF9lE:4zMzdc_GQZn-uFixakU4Ga_VAZUkjrPdB1d7K3bP2QQ	2024-06-20 09:50:20.134027+00
dlzemt6v6ukvkctctqprkn7gdgu1j2lb	.eJxVjDEOwjAQBP_iGlm-YJ8PSnreEK2TMwkgR4qTCvF3iJQC2p2ZfZkW6zK0a9W5HXtzNo05_G4J3UPLBvo7ym2y3VSWeUx2U-xOq71OvT4vu_t3MKAO35roGMl57wKEVDRHzYwgnKQRoUzw5FIOEcQhsorrAhQ4NcwAB_P-AL0pNz8:1sM4ML:z3wIXBNb3sJLO3l_-GsLQ9HHf5BMrchST4SOYFdH0nA	2024-07-09 11:29:13.223956+00
jdk4zc7yj8ka1gbx2k8s89x4vhecopz2	.eJxVjDEOwjAQBP_iGlm-YJ8PSnreEK2TMwkgR4qTCvF3iJQC2p2ZfZkW6zK0a9W5HXtzNo05_G4J3UPLBvo7ym2y3VSWeUx2U-xOq71OvT4vu_t3MKAO35roGMl57wKEVDRHzYwgnKQRoUzw5FIOEcQhsorrAhQ4NcwAB_P-AL0pNz8:1sM9Os:tYlIAQgZVNCs0Y1uLCiUyKOtilB4m4gGVC4nIGJpaAE	2024-07-09 16:52:10.529013+00
gi3j1i1ky7w158zg6uur7abin61dwlvg	.eJxVjMsOwiAUBf-FtSFcGii4dO83kPsAqRqalHZl_Hdt0oVuz8ycl0q4rTVtPS9pEnVWoE6_GyE_ctuB3LHdZs1zW5eJ9K7og3Z9nSU_L4f7d1Cx12_NFMCOYxnM4AqGYpg9sYAJNnouJOR8BCTP0QFTAV8QrAvRBPJCWb0_9k04jg:1sMAHq:CAx2verzMFVgMOEKnBCWJvgn-NmYv22CrelMrRk4CrI	2024-07-09 17:48:58.414904+00
oc5ih5y31dweg7142zp9j2z5wim5mrdt	.eJxVjMsOwiAQRf-FtSEFeQwu3fcbyMBMpWogKe3K-O_apAvd3nPOfYmI21ri1nmJM4mLOIvT75YwP7jugO5Yb03mVtdlTnJX5EG7HBvx83q4fwcFe_nWwSZrhqySocEl8qCMDsR5QgA2Gp1Ljr1SBhlAg3cevdEZAoHHyYJ4fwDcwTeT:1sMNUd:R7R9VIVBIRjI5dPf7kcmMzl01fsd2kSrJv1sfyBPFZI	2024-07-10 07:55:03.61532+00
syw4hv672tkk0u4tsgkzg9w8huvwpw7e	.eJxVjMsOwiAQRf-FtSEMj6G6dO83kOkAUjWQlHZl_HfbpAvd3nPOfYtA61LC2tMcpiguAsTpdxuJn6nuID6o3pvkVpd5GuWuyIN2eWsxva6H-3dQqJet5kSoyRFbjVpZ5bMZHILPmRUhbwQcGT5rw9bTYCB7TgBsbETO4MTnC-PqN-U:1sMNX4:KeOhb38Pjv4cyr20FkUSd_PC7ytLVlgQq493ho4peJE	2024-07-10 07:57:34.550461+00
jp26p7qbegf6n3swk2eg4tp39880b56m	.eJxVjMsOwiAQRf-FtSEMj6G6dO83kOkAUjWQlHZl_HfbpAvd3nPOfYtA61LC2tMcpiguAsTpdxuJn6nuID6o3pvkVpd5GuWuyIN2eWsxva6H-3dQqJet5kSoyRFbjVpZ5bMZHILPmRUhbwQcGT5rw9bTYCB7TgBsbETO4MTnC-PqN-U:1sMNYi:SDY8WeT3qYZhJlXnyhakylIydL9q-ktzBijfWBarBCo	2024-07-10 07:59:16.224174+00
ruollxwa5fx5n9gafv9z251vga25dk28	.eJxVjMsOwiAQRf-FtSEMj6G6dO83kOkAUjWQlHZl_HfbpAvd3nPOfYtA61LC2tMcpiguAsTpdxuJn6nuID6o3pvkVpd5GuWuyIN2eWsxva6H-3dQqJet5kSoyRFbjVpZ5bMZHILPmRUhbwQcGT5rw9bTYCB7TgBsbETO4MTnC-PqN-U:1sMOXe:juszzUQr5rIO5gAniIINvIjz0wPw4iDAlCIMYJ02LG8	2024-07-10 09:02:14.085792+00
4n4wg6s2ja5csoa43xzxm3x2kskyqanp	.eJxVjMsOwiAQRf-FtSEFeQwu3fcbyMBMpWogKe3K-O_apAvd3nPOfYmI21ri1nmJM4mLOIvT75YwP7jugO5Yb03mVtdlTnJX5EG7HBvx83q4fwcFe_nWwSZrhqySocEl8qCMDsR5QgA2Gp1Ljr1SBhlAg3cevdEZAoHHyYJ4fwDcwTeT:1sMUWG:L6g4ivquSmBUr9nkAwAaxrGxZzTg36O_pVXC2vZCwFE	2024-07-10 15:25:12.508062+00
kr48eez4igvqz4lgywfqd5wq2yrstm4d	.eJxVjMsOwiAQRf-FtSEMj6G6dO83kOkAUjWQlHZl_HfbpAvd3nPOfYtA61LC2tMcpiguAsTpdxuJn6nuID6o3pvkVpd5GuWuyIN2eWsxva6H-3dQqJet5kSoyRFbjVpZ5bMZHILPmRUhbwQcGT5rw9bTYCB7TgBsbETO4MTnC-PqN-U:1sRmSW:J_uPJOsuo0w3WRVdSXurdSXDG7xNt3eBtwp-APFiJv0	2024-07-25 05:35:12.642543+00
bfxk5kx9ooiwe5ir838ipvm5pm18cnbq	.eJxVjMsOwiAQRf-FtSEMj6G6dO83kOkAUjWQlHZl_HfbpAvd3nPOfYtA61LC2tMcpiguAsTpdxuJn6nuID6o3pvkVpd5GuWuyIN2eWsxva6H-3dQqJet5kSoyRFbjVpZ5bMZHILPmRUhbwQcGT5rw9bTYCB7TgBsbETO4MTnC-PqN-U:1sSAFJ:CpWSZocyAi7UfmvEujtOhvvMeliLAOmR-bmRR_yXBlw	2024-07-26 06:59:09.66284+00
3c5a43bcrlkjzbnsnxe7r7jh0yptxlwc	.eJxVjMsOwiAQRf-FtSEMj6G6dO83kOkAUjWQlHZl_HfbpAvd3nPOfYtA61LC2tMcpiguAsTpdxuJn6nuID6o3pvkVpd5GuWuyIN2eWsxva6H-3dQqJet5kSoyRFbjVpZ5bMZHILPmRUhbwQcGT5rw9bTYCB7TgBsbETO4MTnC-PqN-U:1sTypd:kJzES7FzRev0YllRCQnQehHed-Oqspcbr7drACxmYtM	2024-07-31 07:12:09.207888+00
pgvqttz705djwuq6brhjvv33lj79para	.eJxVjMsOwiAQRf-FtSEMj6G6dO83kOkAUjWQlHZl_HfbpAvd3nPOfYtA61LC2tMcpiguAsTpdxuJn6nuID6o3pvkVpd5GuWuyIN2eWsxva6H-3dQqJet5kSoyRFbjVpZ5bMZHILPmRUhbwQcGT5rw9bTYCB7TgBsbETO4MTnC-PqN-U:1sTz36:bWvQfCMHYhsnNMymZGUCmy2fAwYIXFBSrYBMX5QUpu4	2024-07-31 07:26:04.148391+00
cjs0018t1ky7qwp15ufry06g3ste4jx3	.eJxVjMsOwiAQRf-FtSEMj6G6dO83kOkAUjWQlHZl_HfbpAvd3nPOfYtA61LC2tMcpiguAsTpdxuJn6nuID6o3pvkVpd5GuWuyIN2eWsxva6H-3dQqJet5kSoyRFbjVpZ5bMZHILPmRUhbwQcGT5rw9bTYCB7TgBsbETO4MTnC-PqN-U:1sU20f:iN6HjSiGjrxOoPsBaaskYNRPIN17HPeu-6IEif1xyx4	2024-07-31 10:35:45.329151+00
40xskn094zmlp4unf26onqvhva2vpuvk	.eJxVjMsOwiAQRf-FtSEMj6G6dO83kOkAUjWQlHZl_HfbpAvd3nPOfYtA61LC2tMcpiguAsTpdxuJn6nuID6o3pvkVpd5GuWuyIN2eWsxva6H-3dQqJet5kSoyRFbjVpZ5bMZHILPmRUhbwQcGT5rw9bTYCB7TgBsbETO4MTnC-PqN-U:1sa7Uu:DrT_n7jkKBdZuPqzqgFqL9G395COfv8cMsrvDqLiE08	2024-08-17 05:40:08.310879+00
36q8nbp3adeo1xie5ndtxqxhfqctnuze	.eJxVjMsOwiAQRf-FtSEMj6G6dO83kOkAUjWQlHZl_HfbpAvd3nPOfYtA61LC2tMcpiguAsTpdxuJn6nuID6o3pvkVpd5GuWuyIN2eWsxva6H-3dQqJet5kSoyRFbjVpZ5bMZHILPmRUhbwQcGT5rw9bTYCB7TgBsbETO4MTnC-PqN-U:1sar0u:MbrMN0Ux7d0N9ZDpiAOK2z65peJ7RknSbtSYlk7fIz4	2024-08-19 06:16:12.107545+00
u8023twfp1x1fsfw7pnkvsrhdli1cfvr	.eJxVjMsOwiAQRf-FtSEMj6G6dO83kOkAUjWQlHZl_HfbpAvd3nPOfYtA61LC2tMcpiguAsTpdxuJn6nuID6o3pvkVpd5GuWuyIN2eWsxva6H-3dQqJet5kSoyRFbjVpZ5bMZHILPmRUhbwQcGT5rw9bTYCB7TgBsbETO4MTnC-PqN-U:1sfZ48:aj3xhu2P42oVsu3RO5Qnu4XVoDQlwn12JjvW3zbXJl4	2024-09-01 06:07:00.22076+00
\.


--
-- Data for Name: jet_bookmark; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.jet_bookmark (id, url, title, user_id, date_add) FROM stdin;
\.


--
-- Data for Name: jet_pinnedapplication; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.jet_pinnedapplication (id, app_label, user_id, date_add) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 60, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 3, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 8, true);


--
-- Name: avito_account_analyticschema_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.avito_account_analyticschema_id_seq', 1, false);


--
-- Name: avito_account_avitoaccount_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.avito_account_avitoaccount_id_seq', 1, false);


--
-- Name: avito_account_criterion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.avito_account_criterion_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 90, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 15, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 41, true);


--
-- Name: jet_bookmark_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.jet_bookmark_id_seq', 1, false);


--
-- Name: jet_pinnedapplication_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.jet_pinnedapplication_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: avito_account_analyticschema avito_account_analyticschema_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.avito_account_analyticschema
    ADD CONSTRAINT avito_account_analyticschema_pkey PRIMARY KEY (id);


--
-- Name: avito_account_avitoaccount avito_account_avitoaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.avito_account_avitoaccount
    ADD CONSTRAINT avito_account_avitoaccount_pkey PRIMARY KEY (id);


--
-- Name: avito_account_criterion avito_account_criterion_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.avito_account_criterion
    ADD CONSTRAINT avito_account_criterion_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: jet_bookmark jet_bookmark_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.jet_bookmark
    ADD CONSTRAINT jet_bookmark_pkey PRIMARY KEY (id);


--
-- Name: jet_pinnedapplication jet_pinnedapplication_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.jet_pinnedapplication
    ADD CONSTRAINT jet_pinnedapplication_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: avito_account_analyticschema_created_by_id_93792754; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX avito_account_analyticschema_created_by_id_93792754 ON public.avito_account_analyticschema USING btree (created_by_id);


--
-- Name: avito_account_avitoaccount_analytic_schema_id_6acac0fa; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX avito_account_avitoaccount_analytic_schema_id_6acac0fa ON public.avito_account_avitoaccount USING btree (analytic_schema_id);


--
-- Name: avito_account_avitoaccount_company_id_31f98c67; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX avito_account_avitoaccount_company_id_31f98c67 ON public.avito_account_avitoaccount USING btree (company_id);


--
-- Name: avito_account_criterion_created_by_id_3d20689c; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX avito_account_criterion_created_by_id_3d20689c ON public.avito_account_criterion USING btree (created_by_id);


--
-- Name: avito_account_criterion_schema_id_53e8baa3; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX avito_account_criterion_schema_id_53e8baa3 ON public.avito_account_criterion USING btree (schema_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: jet_bookmark_user_id_8efdc332; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX jet_bookmark_user_id_8efdc332 ON public.jet_bookmark USING btree (user_id);


--
-- Name: jet_pinnedapplication_user_id_7765bcf9; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX jet_pinnedapplication_user_id_7765bcf9 ON public.jet_pinnedapplication USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: avito_account_analyticschema avito_account_analyt_created_by_id_93792754_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.avito_account_analyticschema
    ADD CONSTRAINT avito_account_analyt_created_by_id_93792754_fk_auth_user FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: avito_account_avitoaccount avito_account_avitoa_analytic_schema_id_6acac0fa_fk_avito_acc; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.avito_account_avitoaccount
    ADD CONSTRAINT avito_account_avitoa_analytic_schema_id_6acac0fa_fk_avito_acc FOREIGN KEY (analytic_schema_id) REFERENCES public.avito_account_analyticschema(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: avito_account_avitoaccount avito_account_avitoaccount_company_id_31f98c67_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.avito_account_avitoaccount
    ADD CONSTRAINT avito_account_avitoaccount_company_id_31f98c67_fk_auth_user_id FOREIGN KEY (company_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: avito_account_criterion avito_account_criter_schema_id_53e8baa3_fk_avito_acc; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.avito_account_criterion
    ADD CONSTRAINT avito_account_criter_schema_id_53e8baa3_fk_avito_acc FOREIGN KEY (schema_id) REFERENCES public.avito_account_analyticschema(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: avito_account_criterion avito_account_criterion_created_by_id_3d20689c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.avito_account_criterion
    ADD CONSTRAINT avito_account_criterion_created_by_id_3d20689c_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jet_bookmark jet_bookmark_user_id_8efdc332_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.jet_bookmark
    ADD CONSTRAINT jet_bookmark_user_id_8efdc332_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jet_pinnedapplication jet_pinnedapplication_user_id_7765bcf9_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.jet_pinnedapplication
    ADD CONSTRAINT jet_pinnedapplication_user_id_7765bcf9_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

