# Generated by Django 5.0.4 on 2025-05-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=127, verbose_name='Модель')),
                ('tokens_completion', models.IntegerField(verbose_name='Токены выполнениы')),
                ('tokens_prompt', models.IntegerField(verbose_name='Токены промпта')),
                ('completion_detail', models.CharField(blank=True, max_length=255, verbose_name='Детали выполнения')),
                ('prompt_detail', models.CharField(blank=True, max_length=255, verbose_name='Детали промпта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
    ]
