# Generated by Django 5.0.4 on 2025-07-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='tag',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='model',
            field=models.CharField(db_index=True, max_length=127, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='tokens_completion',
            field=models.IntegerField(verbose_name='Токены выполнения'),
        ),
    ]
