from environs import env


TEST_DJANGO_HOST = env.str("TEST_DJANGO_HOST")

SELLER_AVITO_ACCOUNT_ID = env.int("TEST_SELLER_AVITO_ACCOUNT_ID", None)
CUSTOMER_AVITO_ACCOUNT_ID = env.int("TEST_CUSTOMER_AVITO_ACCOUNT_ID")
AVITO_CHAT_ID = env.str("TEST_AVITO_CHAT_ID", None)

TELEGRAM_BOT_TOKEN = env.str("TELEGRAM_BOT_TOKEN", "")
SUMMARY_CHAT_ID: int | None = env.int("TEST_SUMMARY_CHAT_ID", None)

BOT_HANDLE_MESSAGE_WAIT_TIME_SEC = 30
