# Generated by Django 5.0.4 on 2025-04-14 11:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoOrigin',
            fields=[
                ('amo_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Идентификатор в системе Amo')),
                ('code', models.CharField(max_length=64, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Amo-источник',
                'verbose_name_plural': 'Amo-источники',
            },
        ),
        migrations.CreateModel(
            name='AmoAccount',
            fields=[
                ('amo_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор в системе amo')),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID телеграм-чата')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Домен')),
                ('amojo_id', models.CharField(max_length=255, unique=True, verbose_name='Идентификатор в системе amojo')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('amo_login', models.CharField(max_length=255, verbose_name='Логин')),
                ('amo_password', models.TextField(verbose_name='Пароль')),
                ('access_token', models.TextField(verbose_name='Access-токен')),
                ('refresh_token', models.TextField(verbose_name='Refresh-токен')),
                ('amojo_access_token', models.TextField(null=True, verbose_name='Access-токен для amojo сервиса')),
                ('cookies_session_id', models.TextField(null=True, verbose_name='Id сессии для ajax запросов')),
                ('cookies_csrf_token', models.TextField(null=True, verbose_name='CSRF-токен для ajax запросов')),
                ('cookies_access_token', models.TextField(null=True, verbose_name='Access-токен для ajax запросов')),
                ('cookies_refresh_token', models.TextField(null=True, verbose_name='Refresh-токен для ajax запросов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Когда обновлен')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
            ],
            options={
                'verbose_name': 'Amo-аккаунт',
                'verbose_name_plural': 'Amo-аккаунты',
            },
        ),
        migrations.CreateModel(
            name='AmoChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активирован')),
                ('waiting_minutes', models.PositiveSmallIntegerField(help_text='Укажите количество минут от 1 до 120', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Ожидание ответа от менеджера(минуты)')),
                ('shutdown_after_manager', models.BooleanField(default=False, verbose_name='Выключаться после менеджера')),
                ('work_time_from', models.TimeField(verbose_name='Начало работы МСК (Пн-Вс)')),
                ('work_time_to', models.TimeField(verbose_name='Окончание работы МСК (Пн-Вс)')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя бота')),
                ('role_and_tasks', models.TextField(blank=True, verbose_name='Роль и задачи')),
                ('behaviour_style', models.TextField(blank=True, verbose_name='Стиль поведения во время общения')),
                ('company_and_products', models.TextField(blank=True, verbose_name='Описание компании и продуктов')),
                ('important_conditions', models.TextField(blank=True, verbose_name='На какие важные условия боту обратить внимание')),
                ('links_and_contacts', models.TextField(blank=True, verbose_name='Полезные ссылки и контакты')),
                ('pipeline_status_update_rules', models.TextField(blank=True, verbose_name='Правила обновления этапа воронки')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amoaccount', verbose_name='Amo-аккаунт')),
            ],
            options={
                'verbose_name': 'Amo чат-бот',
                'verbose_name_plural': 'Amo чат-боты',
            },
        ),
        migrations.CreateModel(
            name='FillableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('entity', models.CharField(choices=[('CONTACT', 'Контакт'), ('LEAD', 'Сделка')], verbose_name='К чему относится')),
                ('description', models.TextField(verbose_name='Описание для промпта')),
                ('required', models.BooleanField(verbose_name='Обязательное')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amochatbot', verbose_name='Чат-бот заполнитель поля')),
            ],
            options={
                'verbose_name': 'Заполняемое поле',
                'verbose_name_plural': 'Заполняемые поля',
            },
        ),
        migrations.CreateModel(
            name='AmoChatBotTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
                ('tokens_completion', models.IntegerField(default=0, verbose_name='Токены на вычисления')),
                ('tokens_prompt', models.IntegerField(default=0, verbose_name='Токены на контекст')),
                ('object_id', models.CharField(db_index=True, max_length=255, verbose_name='Идентификатор объекта')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING_DATA', 'Preparing Data'), ('ANSWER_GENERATION', 'Answer Generation'), ('ANSWER_SENDING', 'Answer Sending'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled'), ('INTERRUPTED', 'Interrupted')], db_index=True, default='PENDING', verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создана задача')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Когда создана задача')),
                ('lead_id', models.CharField(db_index=True, max_length=15, verbose_name='Идентификатор сделки')),
                ('contact_id', models.CharField(db_index=True, max_length=15, verbose_name='Идентификатор контакта')),
                ('chat_id', models.CharField(db_index=True, max_length=255, verbose_name='Идентификатор чата')),
                ('talk_id', models.IntegerField(db_index=True, verbose_name='Идентификатор разговора')),
                ('message_id', models.CharField(db_index=True, max_length=255, verbose_name='Идентификатор сообщения')),
                ('message_created_at', models.DateTimeField(verbose_name='Когда создано сообщение')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('sent_report', models.BooleanField(default=False, verbose_name='Отчет был отправлен')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amoaccount', verbose_name='Amo-аккаунт')),
                ('chatbot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amo.amochatbot', verbose_name='чат-бот')),
            ],
            options={
                'verbose_name': 'Amo-задача',
                'verbose_name_plural': 'Amo-задачи',
                'unique_together': {('account', 'chat_id', 'message_id')},
            },
        ),
        migrations.CreateModel(
            name='AmoChatbotOriginLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amochatbot', verbose_name='Чат-бот')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amoorigin', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Связь бот-источник',
                'verbose_name_plural': 'Связи бот-источник',
                'unique_together': {('chatbot', 'origin')},
            },
        ),
        migrations.CreateModel(
            name='AmoPipelineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_id', models.BigIntegerField(db_index=True, verbose_name='Идентификатор воронки в системе Amo')),
                ('pipeline_name', models.CharField(max_length=255, verbose_name='Название воронки')),
                ('amo_id', models.BigIntegerField(db_index=True, verbose_name='Идентификатор этапа в системе Amo')),
                ('name', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amoaccount', verbose_name='Amo-аккаунт')),
                ('chat_bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amo.amochatbot', verbose_name='Чат-бот обработчик сделок')),
            ],
            options={
                'verbose_name': 'Этап Amo-воронки',
                'verbose_name_plural': 'Этапы Amo-воронок',
                'unique_together': {('account', 'pipeline_id', 'amo_id')},
            },
        ),
        migrations.CreateModel(
            name='AmoTalkLeadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_id', models.BigIntegerField(db_index=True, verbose_name='Идентификатор разговора в системе амо')),
                ('lead_id', models.BigIntegerField(db_index=True, verbose_name='Идентификатор сделки в системе амо')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amoaccount', verbose_name='Amo-аккаунт')),
            ],
            options={
                'verbose_name': 'Связи разговор-сделка',
                'unique_together': {('talk_id', 'lead_id')},
            },
        ),
    ]
