# Generated by Django 5.0.4 on 2024-12-14 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avito_account', '0010_avitoaccount_balance_alerting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmocrmAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создано')),
                ('integration_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito_account.avitoaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
