# Generated by Django 5.0.4 on 2025-03-26 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoAccount',
            fields=[
                ('amo_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор в системе amo')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Домен')),
                ('amojo_id', models.CharField(max_length=255, unique=True, verbose_name='Идентификатор в системе amojo')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('access_token', models.TextField(verbose_name='Access-токен')),
                ('refresh_token', models.TextField(verbose_name='Refresh-токен')),
                ('amojo_access_token', models.TimeField(null=True, verbose_name='Access-токен для amojo сервиса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Когда обновлен')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
            ],
            options={
                'verbose_name': 'Amo-аккаунт',
                'verbose_name_plural': 'Amo-аккаунты',
            },
        ),
    ]
