# Generated by Django 5.0.4 on 2025-03-26 13:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активирован')),
                ('total_info', models.TextField(verbose_name='Общая информация')),
                ('rules', models.TextField(verbose_name='Правила при общении')),
                ('checkpoints', models.TextField(verbose_name='Шаги при общении')),
                ('target_action', models.TextField(default='Взять номер телефона клиента для связи', verbose_name='Целевое действие')),
                ('waiting_minutes', models.PositiveSmallIntegerField(help_text='Укажите количество минут от 1 до 120', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Ожидание ответа от менеджера(минуты)')),
                ('shutdown_after_manager', models.BooleanField(default=False, verbose_name='Выключаться после менеджера')),
                ('work_time_from', models.TimeField(verbose_name='Начало работы МСК (Пн-Вс)')),
                ('work_time_to', models.TimeField(verbose_name='Окончание работы МСК (Пн-Вс)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amoaccount', verbose_name='Amo-аккаунт')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AmoChatBotTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=255, verbose_name='Идентификатор объекта')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING_DATA', 'Preparing Data'), ('ANSWER_GENERATION', 'Answer Generation'), ('ANSWER_SENDING', 'Answer Sending'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled'), ('INTERRUPTED', 'Interrupted')], db_index=True, default='PENDING', verbose_name='Статус')),
                ('chat_id', models.CharField(db_index=True, max_length=255, verbose_name='Идентификатор чата')),
                ('message_id', models.CharField(db_index=True, max_length=255, verbose_name='Идентификатор сообщения')),
                ('talk_id', models.IntegerField(db_index=True, verbose_name='Идентификатор разговора')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amoaccount', verbose_name='Amo-аккаунт')),
            ],
            options={
                'verbose_name': 'Amo-сообщение',
                'verbose_name_plural': 'Amo-сообщения',
                'unique_together': {('account', 'chat_id', 'message_id')},
            },
        ),
    ]
