# Generated by Django 5.0.4 on 2025-04-15 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amopipelinestatus',
            name='chat_bot',
        ),
        migrations.RemoveField(
            model_name='fillablefield',
            name='required',
        ),
        migrations.AddField(
            model_name='amochatbot',
            name='message_when_qualification',
            field=models.TextField(blank=True, verbose_name='Сообщение при достижении квалификации'),
        ),
        migrations.AddField(
            model_name='amochatbot',
            name='new_status_when_qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amo.amopipelinestatus', verbose_name='Этап воронки при достижении квалификации'),
        ),
        migrations.AddField(
            model_name='fillablefield',
            name='required_for_qualification',
            field=models.BooleanField(default=False, verbose_name='Нужно для квалификации'),
        ),
        migrations.CreateModel(
            name='AmoPipelineStatusChatbotLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_qualification', models.BooleanField(default=False, verbose_name='Проверять квалификацию')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amochatbot', verbose_name='Чат-бот')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amo.amopipelinestatus', verbose_name='Этап воронки')),
            ],
            options={
                'verbose_name': 'Связь бот-воронка',
                'verbose_name_plural': 'Связи бот-воронка',
            },
        ),
    ]
