# Generated by Django 5.0.4 on 2024-12-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amocrmaccount',
            options={'verbose_name': 'Амосрм аккаунт', 'verbose_name_plural': 'Амосрм аккаунты'},
        ),
        migrations.RemoveField(
            model_name='amocrmaccount',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='amocrmaccount',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amocrmaccount',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
