# Generated by Django 5.0.4 on 2025-04-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0002_remove_amopipelinestatus_chat_bot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amochatbot',
            name='change_status_only_when_qualification',
            field=models.BooleanField(default=True, verbose_name='Менять статус только при достижении квалификации'),
        ),
        migrations.AddField(
            model_name='amochatbot',
            name='work_on_fri',
            field=models.BooleanField(default=True, verbose_name='Работает в пт'),
        ),
        migrations.AddField(
            model_name='amochatbot',
            name='work_on_mon',
            field=models.BooleanField(default=True, verbose_name='Работает в пн'),
        ),
        migrations.AddField(
            model_name='amochatbot',
            name='work_on_sat',
            field=models.BooleanField(default=True, verbose_name='Работает в сб'),
        ),
        migrations.AddField(
            model_name='amochatbot',
            name='work_on_sun',
            field=models.BooleanField(default=True, verbose_name='Работает в вскр'),
        ),
        migrations.AddField(
            model_name='amochatbot',
            name='work_on_thu',
            field=models.BooleanField(default=True, verbose_name='Работает в чт'),
        ),
        migrations.AddField(
            model_name='amochatbot',
            name='work_on_tue',
            field=models.BooleanField(default=True, verbose_name='Работает во вт'),
        ),
        migrations.AddField(
            model_name='amochatbot',
            name='work_on_wed',
            field=models.BooleanField(default=True, verbose_name='Работает в ср'),
        ),
    ]
