# Generated by Django 5.0.4 on 2025-03-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0002_amochatbot_amochatbottask'),
    ]

    operations = [
        migrations.AddField(
            model_name='amochatbottask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-03-01 00:00', verbose_name='Когда создана задача'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amochatbottask',
            name='message_created_at',
            field=models.DateTimeField(default='2025-02-28 23:59', verbose_name='Когда создано сообщение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amochatbottask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда создана задача'),
        ),
    ]
