# Generated by Django 5.0.4 on 2024-12-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0002_alter_amocrmaccount_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amocrmaccount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='amocrmaccount',
            name='created_by',
        ),
    ]
