# Generated by Django 5.0.4 on 2024-12-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0003_remove_amocrmaccount_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amocrmaccount',
            name='authorization_key',
            field=models.CharField(default=123, max_length=255, verbose_name='Код авторизации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmaccount',
            name='secret_key',
            field=models.CharField(default=123, max_length=255, verbose_name='Секретный ключ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amocrmaccount',
            name='integration_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID интеграции'),
        ),
    ]
