# Generated by Django 5.0.4 on 2025-03-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0003_amochatbottask_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amoaccount',
            name='cookies_access_token',
            field=models.TextField(null=True, verbose_name='Access-токен для ajax запросов'),
        ),
        migrations.AddField(
            model_name='amoaccount',
            name='cookies_csrf_token',
            field=models.TextField(null=True, verbose_name='CSRF-токен для ajax запросов'),
        ),
        migrations.AddField(
            model_name='amoaccount',
            name='cookies_refresh_token',
            field=models.TextField(null=True, verbose_name='Refresh-токен для ajax запросов'),
        ),
        migrations.AddField(
            model_name='amoaccount',
            name='cookies_session_id',
            field=models.TextField(null=True, verbose_name='Id сессии для ajax запросов'),
        ),
        migrations.AddField(
            model_name='amochatbottask',
            name='lead_id',
            field=models.CharField(db_index=True, default='1', max_length=15, verbose_name='Идентификатор сделки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amoaccount',
            name='amojo_access_token',
            field=models.TextField(null=True, verbose_name='Access-токен для amojo сервиса'),
        ),
    ]
