# Generated by Django 5.0.4 on 2025-05-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0003_amochatbot_change_status_only_when_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amochatbot',
            name='duplicate_instructions',
            field=models.TextField(blank=True, verbose_name='Важные команды еще раз'),
        ),
        migrations.AddField(
            model_name='amochatbot',
            name='prompt_example',
            field=models.TextField(blank=True, verbose_name='Пример промпта'),
        ),
    ]
