# Generated by Django 5.0.4 on 2025-05-03 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0004_amochatbot_duplicate_instructions_and_more'),
        ('transcriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amochatbottask',
            name='file_link',
            field=models.TextField(blank=True, verbose_name='Прикрепленный файл'),
        ),
        migrations.AddField(
            model_name='amochatbottask',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('picture', 'Picture')], default='text', verbose_name='Тип сообщения'),
        ),
        migrations.AlterField(
            model_name='amochatbottask',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст сообщения'),
        ),
        migrations.CreateModel(
            name='AmoTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=255, verbose_name='Идентификатор чата')),
                ('message_id', models.CharField(db_index=True, max_length=255, verbose_name='Идентификатор сообщения')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amoaccount', verbose_name='Амо-аккаунт')),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcriptions.transcription', verbose_name='Транскрипция')),
            ],
        ),
    ]
