# Generated by Django 5.0.4 on 2025-03-28 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0004_amoaccount_cookies_access_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amochatbot',
            options={'verbose_name': 'Amo чат-бот', 'verbose_name_plural': 'Amo чат-боты'},
        ),
        migrations.AddField(
            model_name='amochatbottask',
            name='answer_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ответа'),
        ),
        migrations.AddField(
            model_name='amochatbottask',
            name='chatbot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amo.amochatbot', verbose_name='чат-бот'),
        ),
        migrations.AddField(
            model_name='amochatbottask',
            name='tokens_completion',
            field=models.IntegerField(default=0, verbose_name='Токены на вычисления'),
        ),
        migrations.AddField(
            model_name='amochatbottask',
            name='tokens_prompt',
            field=models.IntegerField(default=0, verbose_name='Токены на контекст'),
        ),
        migrations.CreateModel(
            name='AmoContact',
            fields=[
                ('address', models.TextField(blank=True, default=None, null=True, verbose_name='Адрес клиента')),
                ('mobile', models.TextField(blank=True, default=None, null=True, verbose_name='Мобильный номер')),
                ('whatsapp', models.TextField(blank=True, default=None, null=True, verbose_name='Вацап')),
                ('telegram', models.TextField(blank=True, default=None, null=True, verbose_name='Телеграм')),
                ('email', models.TextField(blank=True, default=None, null=True, verbose_name='Емайл')),
                ('amo_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Идентификатор контакта в системе amo')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amoaccount')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AddField(
            model_name='amochatbottask',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amo.amocontact', verbose_name='Контакт'),
        ),
    ]
