# Generated by Django 5.0.4 on 2024-12-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0004_amocrmaccount_authorization_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amocrmaccount',
            name='redirect_url',
            field=models.CharField(default=1, max_length=255, verbose_name='Ссылка для перенаправления'),
            preserve_default=False,
        ),
    ]
