# Generated by Django 5.0.4 on 2025-03-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0005_alter_amochatbot_options_amochatbottask_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amochatbottask',
            options={'verbose_name': 'Amo-задача', 'verbose_name_plural': 'Amo-задачи'},
        ),
        migrations.AlterModelOptions(
            name='amocontact',
            options={'verbose_name': 'Amo-контакт', 'verbose_name_plural': 'Amo-контакты'},
        ),
        migrations.AddField(
            model_name='amoaccount',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор чата для отчетов'),
        ),
        migrations.AddField(
            model_name='amochatbottask',
            name='sent_report',
            field=models.BooleanField(default=False, verbose_name='Отчет был отправлен'),
        ),
    ]
