# Generated by Django 5.0.4 on 2024-12-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0005_amocrmaccount_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='amocrmaccount',
            name='subdomain',
            field=models.CharField(default=1, help_text='первое слово в ссылке на ваш кабинет', max_length=255, verbose_name='Субдомен'),
            preserve_default=False,
        ),
    ]
