# Generated by Django 5.0.4 on 2025-05-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0005_amochatbottask_file_link_amochatbottask_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amoorigin',
            name='code',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Код'),
        ),
    ]
