# Generated by Django 5.0.4 on 2025-04-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0006_alter_amochatbottask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amoaccount',
            name='amo_login',
            field=models.CharField(default=1, max_length=255, verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amoaccount',
            name='amo_password',
            field=models.TextField(default=1, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
