# Generated by Django 5.0.4 on 2025-05-12 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0006_alter_amoorigin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='amochatbot',
            name='waiting_seconds',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ожидание ответа от менеджера (секунды)'),
        ),
        migrations.AlterField(
            model_name='amochatbot',
            name='name',
            field=models.CharField(db_index=True, default='Безымянный ИИ', max_length=255, verbose_name='Название'),
        ),
    ]
