# Generated by Django 5.0.4 on 2024-12-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0006_amocrmaccount_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amocrmaccount',
            name='integration_id',
            field=models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='ID интеграции'),
        ),
        migrations.AlterField(
            model_name='amocrmaccount',
            name='subdomain',
            field=models.CharField(help_text='первое слово в ссылке на ваш кабинет те abduraufdev для abduraufdev.amocrm.ru', max_length=255, verbose_name='Субдомен'),
        ),
    ]
