# Generated by Django 5.0.4 on 2025-05-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0007_amochatbot_waiting_seconds_alter_amochatbot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amochatbot',
            name='waiting_minutes',
        ),
    ]
