# Generated by Django 5.0.4 on 2025-04-07 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0007_amoaccount_amo_login_amoaccount_amo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='amochatbot',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя бота'),
        ),
        migrations.CreateModel(
            name='AmoPipelineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_id', models.BigIntegerField(db_index=True, verbose_name='Идентификатор воронки в системе Amo')),
                ('pipeline_name', models.CharField(max_length=255, verbose_name='Название воронки')),
                ('amo_id', models.BigIntegerField(db_index=True, verbose_name='Идентификатор этапа в системе Amo')),
                ('name', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amoaccount', verbose_name='Amo-аккаунт')),
                ('chat_bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amo.amochatbot', verbose_name='Чат-бот обработчик сделок')),
            ],
            options={
                'verbose_name': 'Этап Amo-воронки',
                'verbose_name_plural': 'Этапы Amo-воронок',
                'unique_together': {('account', 'pipeline_id', 'amo_id')},
            },
        ),
    ]
