# Generated by Django 5.0.4 on 2025-04-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0008_amochatbot_name_amopipelinestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amopipelinestatus',
            name='chat_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amo.amochatbot', verbose_name='Чат-бот обработчик сделок'),
        ),
        migrations.CreateModel(
            name='LeadFieldsFilledByChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amochatbot', verbose_name='Чат-бот заполнитель поля')),
            ],
            options={
                'verbose_name': 'Поле сделки',
                'verbose_name_plural': 'Поля сделок',
            },
        ),
    ]
