# Generated by Django 5.0.4 on 2025-05-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0008_remove_amochatbot_waiting_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='amochatbot',
            name='message_postfix',
            field=models.TextField(blank=True, default='...', verbose_name='Постфикс сгенерированного сообщения'),
        ),
        migrations.AddField(
            model_name='amochatbot',
            name='message_prefix',
            field=models.TextField(blank=True, verbose_name='Префикс сгенерированного сообщения'),
        ),
    ]
