# Generated by Django 5.0.4 on 2025-05-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0009_amochatbot_message_postfix_amochatbot_message_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amochatbot',
            name='prompt_example',
        ),
    ]
