# Generated by Django 5.0.4 on 2025-04-10 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0009_alter_amopipelinestatus_chat_bot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amochatbottask',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='leadfieldsfilledbychatbot',
            name='chatbot',
        ),
        migrations.RemoveField(
            model_name='amochatbot',
            name='checkpoints',
        ),
        migrations.RemoveField(
            model_name='amochatbot',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='amochatbot',
            name='target_action',
        ),
        migrations.RemoveField(
            model_name='amochatbot',
            name='total_info',
        ),
        migrations.AddField(
            model_name='amochatbot',
            name='behaviour_style',
            field=models.TextField(blank=True, verbose_name='Стиль поведения во время общения'),
        ),
        migrations.AddField(
            model_name='amochatbot',
            name='company_and_products',
            field=models.TextField(blank=True, verbose_name='Описание компании и продуктов'),
        ),
        migrations.AddField(
            model_name='amochatbot',
            name='important_conditions',
            field=models.TextField(blank=True, verbose_name='На какие важные условия боту обратить внимание'),
        ),
        migrations.AddField(
            model_name='amochatbot',
            name='links_and_contacts',
            field=models.TextField(blank=True, verbose_name='Полезные ссылки и контакты'),
        ),
        migrations.AddField(
            model_name='amochatbot',
            name='role_and_tasks',
            field=models.TextField(blank=True, verbose_name='Роль и задачи'),
        ),
        migrations.CreateModel(
            name='FillableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('entity', models.CharField(choices=[('CONTACT', 'Контакт'), ('LEAD', 'Сделка')], verbose_name='К чему относится поле')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amochatbot', verbose_name='Чат-бот заполнитель поля')),
            ],
            options={
                'verbose_name': 'Поле сделки',
                'verbose_name_plural': 'Поля сделок',
            },
        ),
        migrations.DeleteModel(
            name='AmoContact',
        ),
        migrations.DeleteModel(
            name='LeadFieldsFilledByChatBot',
        ),
    ]
