# Generated by Django 5.0.4 on 2025-05-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0010_remove_amochatbot_prompt_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlebleNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(db_index=True, max_length=255, verbose_name='Название источника')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amochatbot', verbose_name='Чат-бот')),
            ],
        ),
    ]
