# Generated by Django 5.0.4 on 2025-04-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0010_remove_amochatbottask_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fillablefield',
            options={'verbose_name': 'Заполняемое поле', 'verbose_name_plural': 'Заполняемые поля'},
        ),
        migrations.AddField(
            model_name='fillablefield',
            name='description',
            field=models.TextField(default='r', verbose_name='Описание поля для промпта'),
            preserve_default=False,
        ),
    ]
