# Generated by Django 5.0.4 on 2025-05-29 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0011_handleblenote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handleblenote',
            options={'verbose_name': 'Обрабатываемая заявка', 'verbose_name_plural': 'Обрабатываемые заявки'},
        ),
        migrations.AddField(
            model_name='amoorigin',
            name='account',
            field=models.ForeignKey(default=28713466, on_delete=django.db.models.deletion.CASCADE, to='amo.amoaccount', verbose_name='Amo-аккаунт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amoorigin',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amoorigin',
            name='origin',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Источник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amoorigin',
            name='origin_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок источника'),
        ),
        migrations.AddField(
            model_name='amoorigin',
            name='source_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название источника'),
        ),
    ]
