# Generated by Django 5.0.4 on 2025-04-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0011_alter_fillablefield_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amochatbot',
            name='pipeline_status_update_rules',
            field=models.TextField(blank=True, verbose_name='Правила обновления этапа воронки'),
        ),
        migrations.AddField(
            model_name='amopipelinestatus',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание этапа для промпта'),
        ),
    ]
