# Generated by Django 5.0.4 on 2025-05-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0012_alter_handleblenote_options_amoorigin_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amoorigin',
            name='code',
        ),
        migrations.AlterField(
            model_name='amochatbottask',
            name='talk_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Идентификатор разговора'),
        ),
    ]
