# Generated by Django 5.0.4 on 2025-06-09 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0013_remove_amoorigin_code_alter_amochatbottask_talk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='amochatbot',
            name='message_when_note_received',
            field=models.TextField(blank=True, verbose_name='Сообщение при получении заявки с сайта'),
        ),
        migrations.AddField(
            model_name='amopipelinestatus',
            name='account_name',
            field=models.CharField(default='blank', max_length=255, verbose_name='Название Amo-аккаунта'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AmoChatCreateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_field', models.CharField(max_length=255, verbose_name='Поле с номером телефона')),
                ('channel_id', models.CharField(help_text="При инициации общения с пользователем, AmoCRM делает запрос '/ajax/v1/chats/create', создающий чат, и передает туда scope_id, состоящий из <channel_id>_<amojo_id>", max_length=63, verbose_name='Идентификатор канала')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amoaccount', verbose_name='Amo-аккаунт')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amoorigin', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Конфиг для создания чата',
                'verbose_name_plural': 'Конфиги для создания чата',
            },
        ),
    ]
