# Generated by Django 5.0.4 on 2025-06-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0014_amochatbot_message_when_note_received_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amochatbottask',
            name='contact_id',
        ),
    ]
