# Generated by Django 5.0.4 on 2025-07-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0015_remove_amochatbottask_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillablefield',
            name='isolated_check',
            field=models.BooleanField(default=False, verbose_name='Проверять отдельно'),
        ),
    ]
