# Generated by Django 5.0.4 on 2025-07-21 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0016_fillablefield_isolated_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Промпт')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amochatbot', verbose_name='Чат-бот')),
            ],
            options={
                'verbose_name': 'Amo-промпт',
                'verbose_name_plural': 'Amo-промпты',
            },
        ),
    ]
