# Generated by Django 5.0.4 on 2025-07-25 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0017_amoprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='amoprompt',
            name='available_since',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Актуально с'),
        ),
        migrations.AddField(
            model_name='amoprompt',
            name='available_until',
            field=models.TimeField(default=datetime.time(23, 59, 59), verbose_name='Актуально до'),
        ),
        migrations.DeleteModel(
            name='HandlebleNote',
        ),
    ]
