# Generated by Django 5.0.4 on 2025-07-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0018_amoprompt_available_since_amoprompt_available_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amochatbottask',
            name='sent_report',
        ),
        migrations.AddField(
            model_name='amochatbottask',
            name='qualification_achieved',
            field=models.BooleanField(default=False, verbose_name='Квалификация достигнута'),
        ),
    ]
