# Generated by Django 5.0.4 on 2025-08-31 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0019_remove_amochatbottask_sent_report_and_more'),
        ('avito_account', '0012_avitoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='amochatbottask',
            name='avito_account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avito_account.avitoaccount', verbose_name='Авито-аккаунт'),
        ),
        migrations.AddField(
            model_name='amochatbottask',
            name='avito_chat_id',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Иеднтификатор чата в системе Авито'),
        ),
        migrations.AddField(
            model_name='amochatbottask',
            name='pipeline_type',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('A5CLIENT', 'A5Client')], default='DEFAULT', max_length=255, verbose_name='Тип пайплайна'),
        ),
    ]
