# Generated by Django 5.0.4 on 2025-09-11 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0020_amochatbottask_avito_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amo_id', models.BigIntegerField(verbose_name='Идентификатор в системе Amo')),
                ('entity', models.CharField(choices=[('CONTACT', 'Контакт'), ('LEAD', 'Сделка')], db_index=True, max_length=255, verbose_name='Сущность')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='Кодовое имя')),
                ('enum', models.BooleanField(verbose_name='Является справочником')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amoaccount', verbose_name='Amo-аккаунт')),
            ],
            options={
                'verbose_name': 'Амо-поле',
                'verbose_name_plural': 'Амо-поля',
                'unique_together': {('account', 'amo_id')},
            },
        ),
        migrations.CreateModel(
            name='AmoFieldEnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amo_id', models.BigIntegerField(verbose_name='Идентфикатор в системе Amo')),
                ('sort', models.IntegerField(verbose_name='Порядковый номер')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enums', to='amo.amofield', verbose_name='Поле')),
            ],
            options={
                'verbose_name': 'Значения справочников',
            },
        ),
    ]
