# Generated by Django 5.0.4 on 2025-09-25 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0021_amofield_amofieldenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amofieldenum',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amofield', verbose_name='Поле'),
        ),
    ]
