# Generated by Django 5.0.4 on 2025-09-29 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0022_alter_amofieldenum_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoCaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('handling_way', models.CharField(choices=[('DEFAULT_PIPELINE', 'Стандартный пайплайн'), ('TRANSFER_TO_PIPELINE_STATUS', 'Переводить на другой этап'), ('IGNORE', 'Игнорировать')], max_length=63, verbose_name='Как обрабатывать')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amochatbot', verbose_name='Чат-бот')),
            ],
            options={
                'verbose_name': 'Тип проблемы',
                'verbose_name_plural': 'Типы проблем',
            },
        ),
    ]
