# Generated by Django 5.0.4 on 2025-09-29 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0023_amocasetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='amocasetype',
            name='pipeline_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amo.amopipelinestatus', verbose_name='Этап воронки'),
        ),
    ]
