# Generated by Django 5.0.4 on 2025-10-27 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0024_amocasetype_pipeline_status'),
        ('sandbox_chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoChatbotSandboxInputChatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandbox_chats.inputchat', verbose_name='Тестовый чат')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amochatbot', verbose_name='Чат-бот')),
            ],
        ),
        migrations.CreateModel(
            name='AmoSandboxSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amochatbot', verbose_name='Чат-бот')),
            ],
        ),
        migrations.CreateModel(
            name='AmoSandboxSessionChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amosandboxsession', verbose_name='запуск песочницы')),
            ],
        ),
        migrations.CreateModel(
            name='AmoSandboxOutputChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('CUSTOMER', 'Клиент'), ('MANAGER', 'Менеджер')], max_length=31, verbose_name='Автор')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image_url', models.TextField(blank=True, verbose_name='URL изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amosandboxsessionchat', verbose_name='Чат')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
