# Generated by Django 5.0.4 on 2025-10-27 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0025_amochatbotsandboxinputchatlink_amosandboxsession_and_more'),
        ('sandbox_chats', '0002_inputchat_answer_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='amosandboxsession',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Завершена'),
        ),
        migrations.AddField(
            model_name='amosandboxsessionchat',
            name='mark',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='amosandboxsessionchat',
            name='template_chat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox_chats.inputchat', verbose_name='Основано на чате'),
        ),
    ]
