# Generated by Django 5.0.4 on 2025-10-27 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0026_amosandboxsession_finished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amosandboxsessionchat',
            name='mark',
        ),
        migrations.CreateModel(
            name='AmoSandboxAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('rate', models.SmallIntegerField(verbose_name='Оценка')),
                ('rate_explanation', models.TextField(verbose_name='Пояснение к оценке')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amosandboxsessionchat', verbose_name='Тестовый ответ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
