# Generated by Django 5.0.4 on 2025-10-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0027_remove_amosandboxsessionchat_mark_amosandboxanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoChatbotSandboxSessionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Связь Амо-чат-бот - Тестовая сессия',
                'verbose_name_plural': 'Связи Амо-чат-бот - Тестовая сессия',
            },
        ),
        migrations.RemoveField(
            model_name='amosandboxanswer',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='amosandboxoutputchatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='amosandboxsession',
            name='chatbot',
        ),
        migrations.RemoveField(
            model_name='amosandboxsessionchat',
            name='session',
        ),
        migrations.RemoveField(
            model_name='amosandboxsessionchat',
            name='template_chat',
        ),
        migrations.AlterModelOptions(
            name='amochatbotsandboxinputchatlink',
            options={'verbose_name': 'Связь Амо-чатбот - Тестовый чат', 'verbose_name_plural': 'Связи Амо-чатбот - Тестовый чат'},
        ),
    ]
