# Generated by Django 5.0.4 on 2025-10-28 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0028_amochatbotsandboxsessionlink_and_more'),
        ('sandbox_chats', '0003_sandboxinputchat_sandboxsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amochatbotsandboxinputchatlink',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandbox_chats.sandboxinputchat', verbose_name='Тестовый чат'),
        ),
        migrations.AddField(
            model_name='amochatbotsandboxsessionlink',
            name='chatbot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amochatbot', verbose_name='Чат-бот'),
        ),
        migrations.AddField(
            model_name='amochatbotsandboxsessionlink',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandbox_chats.sandboxsession', verbose_name='Тестовая сессия'),
        ),
        migrations.DeleteModel(
            name='AmoSandboxAnswer',
        ),
        migrations.DeleteModel(
            name='AmoSandboxOutputChatMessage',
        ),
        migrations.DeleteModel(
            name='AmoSandboxSession',
        ),
        migrations.DeleteModel(
            name='AmoSandboxSessionChat',
        ),
    ]
