# Generated by Django 5.0.4 on 2025-10-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0029_alter_amochatbotsandboxinputchatlink_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amochatbottask',
            name='answered_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Когда отвечено'),
        ),
    ]
