# Generated by Django 5.0.4 on 2025-10-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0030_amochatbottask_answered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='amochatbottask',
            name='cancel_reason',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Причина отмены'),
        ),
    ]
