# Generated by Django 5.0.4 on 2024-11-04 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avito_account', '0008_alter_analyticschema_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('total_info', models.TextField(verbose_name='Общая информация')),
                ('rules', models.TextField(verbose_name='Правила при общении')),
                ('checkpoints', models.TextField(verbose_name='Шаги при общении')),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistants', to='avito_account.avitoaccount', verbose_name='ИИ асистент')),
            ],
            options={
                'verbose_name': 'ИИ асистент',
                'verbose_name_plural': 'ИИ асисстенты',
            },
        ),
    ]
