# Generated by Django 5.0.4 on 2024-11-04 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_messaging', '0001_initial'),
        ('avito_account', '0008_alter_analyticschema_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiassistant',
            name='avito_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistants', to='avito_account.avitoaccount', verbose_name='ИИ асистент'),
        ),
    ]
