# Generated by Django 5.0.4 on 2024-11-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_messaging', '0002_alter_aiassistant_avito_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiassistant',
            name='active',
        ),
        migrations.AddField(
            model_name='aiassistant',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активирован'),
        ),
    ]
