# Generated by Django 5.0.4 on 2025-03-26 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbottasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtaskmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Когда создана задача'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testtaskmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда создана задача'),
        ),
    ]
