# Generated by Django 5.0.4 on 2024-12-09 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avito_account', '0010_avitoaccount_balance_alerting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('data', models.JSONField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito_account.avitoaccount')),
            ],
        ),
    ]
