# Generated by Django 5.0.4 on 2025-02-25 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixAccount',
            fields=[
                ('domain', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Домен')),
                ('access_token', models.TextField(verbose_name='Access-токен')),
                ('refresh_token', models.TextField(verbose_name='Токен обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitrix_account', to=settings.AUTH_USER_MODEL, verbose_name='Владелец аккаунта')),
            ],
            options={
                'verbose_name': 'Аккаунт Битрикс24',
                'verbose_name_plural': 'Аккаунты Битрикс24',
            },
        ),
        migrations.CreateModel(
            name='AIChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активирован')),
                ('total_info', models.TextField(verbose_name='Общая информация')),
                ('rules', models.TextField(verbose_name='Правила при общении')),
                ('checkpoints', models.TextField(verbose_name='Шаги при общении')),
                ('target_action', models.TextField(default='Взять номер телефона клиента для связи', verbose_name='Целевое действие')),
                ('work_time_from', models.TimeField(verbose_name='Начало работы МСК (Пн-Вс)')),
                ('work_time_to', models.TimeField(verbose_name='Окончание работы МСК (Пн-Вс)')),
                ('bitrix_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitrix.bitrixaccount', verbose_name='Битрикс-аккаунт')),
            ],
            options={
                'verbose_name': 'Чат-бот',
                'verbose_name_plural': 'Чат-боты',
            },
        ),
    ]
