from celery import shared_task

import messaging.api
from avito_account.models.models import AvitoAccount
from base.celery import celery_logger
from chat_bot import ai_utils
from chat_bot.models import AiChatBot
from chat_bot.models import ChatBotTask
from chat_bot.models import DialogTrigger
from chat_bot.models import WorkedTrigger
from chat_bot.utils import avito_api
from chat_bot.utils import avito_messages
from chat_bot.utils import companies_branches
from chat_bot.utils import contacts_saving
from chat_bot.utils import daily_report
from chat_bot.utils import dialog_triggers
from chat_bot.utils import summaries
from chat_bot.utils import summary_sending
from chat_bot.utils import trigger_condition_check
from utils.logging import TraceLogger


@shared_task
def ai_answer_sender_task(
    avito_account_id: int,
    chatbot_id: int,
    chat_id: str,
    message_id: str,
    new_task_id: str,
    *,
    trace_id: str,
) -> None:

    tlogger = TraceLogger(trace_id)
    tlogger.info(f"ai_answer_sender STARTED")

    avito_account = AvitoAccount.objects.get(pk=avito_account_id)
    chatbot = AiChatBot.objects.get(pk=chatbot_id)

    chat = messaging.api.get_chat_last_50_messages_by_chat_id(
        avito_account=avito_account,
        chat_id=chat_id,
        tlogger=tlogger,
    )
    assert "messages" in chat

    new_task = ChatBotTask.objects.get(pk=new_task_id)

    if not avito_messages.is_message_actual(new_task, chat["messages"], tlogger=tlogger):
        tlogger.info(f"Stop handling. Message is not actual (id={message_id})")
        return

    company_branch = companies_branches.define_company_branch(avito_account, chat_id, tlogger=tlogger)
    last_message_id = chat["messages"][-1]["id"]

    if chatbot.read_only:
        ai_answer = ai_utils.parse_contacts(
            chatbot=chatbot,
            chat=chat,
            ask_location=company_branch is None,
            tlogger=tlogger,
        )
        tlogger.info("Chatbot configured to read only")
    else:
        ai_answer = ai_utils.generate_answer_and_parse_contacts(
            ai_assistant=chatbot,
            chat=chat,
            ask_location=company_branch is None,
            tlogger=tlogger,
        )
        ai_answer.answer += "..."

        last_message_id = avito_api.send_message(avito_account, chat_id, ai_answer.answer, tlogger=tlogger).id
        tlogger.info("Answer was sent to avito successfully")

    contacts_saving.task_contacts_save(new_task, ai_answer, is_incoming=True, company_branch=company_branch)
    tlogger.info("AIChatBotTask was updated successfully")

    if summaries.may_send_report(chatbot, ai_answer.contacts, tlogger=tlogger):
        summary_sending.send_summary(avito_account, chat_id, trace_id=tlogger.trace_id)

    if not chatbot.read_only:
        dialog_triggers.initiate_trigger_condition_check(
            chatbot=chatbot,
            chat_id=new_task.chat_id,
            last_message_id=last_message_id,
            tlogger=tlogger,
        )

    tlogger.info("Incoming message handling is finished")


@shared_task
def outgoing_messages_handler(
    chat_id: str,
    message_id: str,
    account_id: int,
    chatbot_id: int,
    task_id: int,
    trace_id: str,
) -> None:

    tlogger = TraceLogger(trace_id)
    tlogger.info("Start outgoing_messages_handler")

    new_task = ChatBotTask.objects.get(pk=task_id)
    avito_account = AvitoAccount.objects.get(pk=account_id)
    chatbot = AiChatBot.objects.get(pk=chatbot_id)

    new_task.is_incoming = False
    new_task.save()

    tasks = list(ChatBotTask.objects.filter(chat_id=chat_id, is_incoming=True).order_by("created_at"))
    answered_from_ai = False

    tlogger.info(f"Current outgoing message: '{new_task.text}'")

    for task in tasks[-5:]:
        if task.answer_text and task.answer_text == new_task.text:
            answered_from_ai = True
            tlogger.info(f"Last answers: " + str([task.answer_text for task in tasks[-5:]]))
            break

    if not answered_from_ai:
        worked_triggers = WorkedTrigger.get_worked_triggers_by_chat(avito_account, chat_id)
        if len(worked_triggers) != 0:
            last_worked_trigger = worked_triggers[len(worked_triggers) - 1].trigger

            if new_task.text == last_worked_trigger.message:
                answered_from_ai = True
                tlogger.info({"Last worked trigger message": last_worked_trigger.message})

    if answered_from_ai:
        tlogger.info("Stop handling. Message generated by ai")
        return

    tlogger.info("Message wrote by manager manually")

    if chatbot.shutdown_after_manager:
        new_task.chat_shutdown_by_user = True
        new_task.save()
        tlogger.info("Bot successfully disabled after manager")

    if not chatbot.send_new_contact_report:
        tlogger.info("Stop handling. Chatbot configured don't send new contacts reports")
        return

    if summaries.new_contact_report_sent(avito_account, chat_id):
        tlogger.info(f"Stop handling. Summary was sent already for chat '{chat_id}'")
        return

    chat = messaging.api.get_chat_last_50_messages_by_chat_id(
        avito_account=avito_account,
        chat_id=chat_id,
        tlogger=tlogger,
    )
    assert "messages" in chat

    last_message_id = chat["messages"][-1]["id"]
    if chat["messages"][-1]["type"] == "system":
        last_message_id = chat["messages"][-2]["id"]

    if last_message_id != message_id:
        tlogger.info(f"Stop handling. Message (id={message_id}) is not actual")
        return

    company_branch = companies_branches.define_company_branch(avito_account, chat_id, tlogger=tlogger)

    ai_answer = ai_utils.parse_contacts(
        chatbot=chatbot,
        chat=chat,
        ask_location=company_branch is None,
        tlogger=tlogger,
    )
    contacts_saving.task_contacts_save(new_task, ai_answer, is_incoming=False, company_branch=company_branch)

    if summaries.may_send_report(chatbot, ai_answer.contacts, tlogger=tlogger):
        summary_sending.send_summary(avito_account, chat_id, trace_id=tlogger.trace_id)

    if not chatbot.read_only:
        dialog_triggers.initiate_trigger_condition_check(
            chatbot=chatbot,
            chat_id=new_task.chat_id,
            last_message_id=last_message_id,
            tlogger=tlogger,
        )

    tlogger.info("Outgoing message handling is finished")


@shared_task
def statistics_sender_main_task():
    tlogger = TraceLogger()

    avito_accounts = AvitoAccount.objects.all()
    tlogger.info(f"statistics_sender_main_task STARTED for {len(avito_accounts)} accounts")

    for avito_account in avito_accounts:
        try:
            daily_report.statistics_for_avito_account.delay(
            # daily_report.statistics_for_avito_account(
                account_id=avito_account.pk,
                trace_id=tlogger.trace_id,
            )
        except Exception as error:
            tlogger.warning(f"Exception when start daily statistics for {avito_account.name}. Got '{error}'")
            celery_logger.exception(f"statistics_sender_main_task error - {error}", exc_info=True)


@shared_task
def dialog_trigger_launcher(trigger_id: int, chat_id: str, last_message_id: str, *, trace_id: str) -> None:
    trigger = DialogTrigger.get(trigger_id)

    tlogger = TraceLogger(trace_id)
    tlogger.info(f"Check condition for trigger '{trigger}' of '{trigger.chatbot.account.name}'")

    chat = messaging.api.get_chat_last_50_messages_by_chat_id(trigger.chatbot.account, chat_id, tlogger=tlogger)
    messages = chat.get("messages", [])
    last_message = None

    for i in range(len(messages) - 1, -1, -1):
        if messages[i]["type"] in {"voice", "text", "location", "link", "image"}:
            last_message = messages[i]
            break

    assert last_message is not None

    if last_message["id"] != last_message_id:
        tlogger.info("Stop handling. Message is not actual")
        return

    if trigger.only_when_client_is_silent and last_message["direction"] == "in":
        tlogger.info("Stop handling. Trigger work only when client is silent, but last message is incoming")
        return

    condition_matched = True

    if trigger.additional_condition.strip():
        condition_check_result = trigger_condition_check.check_trigger_condition(trigger, messages, tlogger=tlogger)
        condition_matched = condition_check_result.condition_match_level == trigger_condition_check.ConditionMatchLevel.FULLY_COMPLETED

        tlogger.info({
            "condition match level": condition_check_result.condition_match_level,
            "explanation": condition_check_result.short_explanation,
        })

    if not condition_matched:
        tlogger.info("Stop handling. Condition not matched")
        return

    sent_message_id = avito_api.send_message(trigger.chatbot.account, chat_id, trigger.message, tlogger=tlogger).id
    WorkedTrigger.create(chat_id, trigger)

    dialog_triggers.initiate_trigger_condition_check(
        chatbot=trigger.chatbot,
        chat_id=chat_id,
        last_message_id=sent_message_id,
        tlogger=tlogger,
    )

    tlogger.info("Triggered")
