from asgiref.sync import async_to_sync
from celery import shared_task

from avito_account.models.models import AvitoAccount
from base.celery import celery_logger
from base.settings import ENVIRONMENT
from chat_bot import ai_utils
from chat_bot.api.core import AvitoMessengerSync
from chat_bot.models import AiChatBot
from chat_bot.models import ChatBotTask
from chat_bot.utils import companies_branches
from chat_bot.utils import contacts_saving
from chat_bot.utils import daily_report
from chat_bot.utils import summaries
from chat_bot.utils import summary_sending
from messaging.api import MessagingAPISync
from utils.logging import TraceLogger


class AiAnswerAvitoClass:
    @staticmethod
    @shared_task
    def ai_answer_sender_task(
        avito_account_id: int,
        chatbot_id: int,
        chat_id: str,
        message_id: str,
        new_task_id: str,
        *,
        trace_id: str,
    ) -> None:

        tlogger = TraceLogger(trace_id)
        tlogger.info(f"ai_answer_sender STARTED")

        avito_account = AvitoAccount.objects.get(pk=avito_account_id)
        chatbot = AiChatBot.objects.get(pk=chatbot_id)

        chat = MessagingAPISync.get_chat_last_50_messages_by_chat_id(
            avito_account=avito_account,
            chat_id=chat_id,
            trace_id=tlogger.trace_id,
        )
        assert "messages" in chat

        # ответ генерируем только если менеджер всё ещё не ответил
        last_message_type = chat["messages"][-1]["type"]
        last_message_id = chat["messages"][-1]["id"]

        if last_message_type == "system":  # тк при номере последним становится уже сообщение с предупреждением
            last_message_type = chat["messages"][-2]["type"]
            last_message_id = chat["messages"][-2]["id"]

        if last_message_id != message_id:
            tlogger.info(f"Stop handling. Message (id={message_id}) is not actual")
            return

        company_branch = companies_branches.define_company_branch(avito_account, chat_id)

        if chatbot.read_only:
            ai_answer = ai_utils.parse_contacts(
                chatbot=chatbot,
                chat=chat,
                ask_location=company_branch is None,
                tlogger=tlogger,
            )

            tlogger.info("Chatbot configured to read only")
        else:
            ai_answer = ai_utils.generate_answer_and_parse_contacts(
                ai_assistant=chatbot,
                chat=chat,
                ask_location=company_branch is None,
                tlogger=tlogger,
            )
            ai_answer.answer += "..."

            AvitoMessengerSync.send_message_to_avito(avito_account, avito_account.pk, chat_id, ai_answer.answer)
            tlogger.info("Answer was sent to avito successfully")

        new_task = ChatBotTask.objects.get(pk=new_task_id)
        contacts_saving.task_contacts_save(new_task, ai_answer, is_incoming=True, company_branch=company_branch)
        tlogger.info("AIChatBotTask was updated successfully")

        if summaries.may_send_report(chatbot, ai_answer.contacts, tlogger=tlogger):
            summary_sending.send_summary(avito_account, chat_id, trace_id=tlogger.trace_id)

        tlogger.info("Incoming message handling is finished")


@shared_task
def outgoing_messages_handler(
    chat_id: str,
    message_id: str,
    account_id: int,
    chatbot_id: int,
    task_id: int,
    trace_id: str,
) -> None:

    tlogger = TraceLogger(trace_id)
    tlogger.info("Start outgoing_messages_handler")

    new_task = ChatBotTask.objects.get(pk=task_id)
    avito_account = AvitoAccount.objects.get(pk=account_id)
    chatbot = AiChatBot.objects.get(pk=chatbot_id)

    new_task.is_incoming = False
    new_task.save()

    tasks = list(ChatBotTask.objects.filter(chat_id=chat_id, is_incoming=True).order_by("created_at"))
    answered_from_ai = False

    for task in tasks[-5:]:
        if task.answer_text and task.answer_text == new_task.text:
            answered_from_ai = True
            break

    tlogger.info(f"Current outgoing message: '{new_task.text}'")
    tlogger.info(f"Last answers: " + str([task.answer_text for task in tasks[-5:]]))

    if answered_from_ai:
        tlogger.info("Stop handling. Message generated by ai")
        return

    tlogger.info("Message wrote by manager manually")

    if chatbot.shutdown_after_manager:
        new_task.chat_shutdown_by_user = True
        new_task.save()
        tlogger.info("Bot successfully disabled after manager")

    if not chatbot.send_new_contact_report:
        tlogger.info("Stop handling. Chatbot configured don't send new contacts reports")
        return

    if summaries.new_contact_report_sent(avito_account, chat_id):
        tlogger.info(f"Stop handling. Summary was sent already for chat '{chat_id}'")
        return

    chat = MessagingAPISync.get_chat_last_50_messages_by_chat_id(
        avito_account=avito_account,
        chat_id=chat_id,
        trace_id=tlogger.trace_id,
    )
    assert "messages" in chat

    last_message_id = chat["messages"][-1]["id"]
    if chat["messages"][-1]["type"] == "system":
        last_message_id = chat["messages"][-2]["id"]

    if last_message_id != message_id:
        tlogger.info(f"Stop handling. Message (id={message_id}) is not actual")
        return

    company_branch = companies_branches.define_company_branch(avito_account, chat_id)

    ai_answer = ai_utils.parse_contacts(
        chatbot=chatbot,
        chat=chat,
        ask_location=company_branch is None,
        tlogger=tlogger,
    )
    contacts_saving.task_contacts_save(new_task, ai_answer, is_incoming=False, company_branch=company_branch)

    if summaries.may_send_report(chatbot, ai_answer.contacts, tlogger=tlogger):
        summary_sending.send_summary(avito_account, chat_id, trace_id=tlogger.trace_id)

    tlogger.info("Outgoing message handling is finished")


@shared_task
def statistics_sender_main_task():
    tlogger = TraceLogger()

    avito_accounts = AvitoAccount.objects.all()
    tlogger.info(f"statistics_sender_main_task STARTED for {len(avito_accounts)} accounts")

    for avito_account in avito_accounts:
        try:
            if ENVIRONMENT == "DEVELOPMENT":
                async_to_sync(avito_account.update_refresh_token_async)()

            daily_report.statistics_for_avito_account.delay(
            # daily_report.statistics_for_avito_account(
                account_id=avito_account.pk,
                trace_id=tlogger.trace_id,
            )
        except Exception as error:
            tlogger.warning(f"Exception when start daily statistics for {avito_account.name}. Got '{error}'")
            celery_logger.exception(f"statistics_sender_main_task error - {error}", exc_info=True)
