# Generated by Django 5.0.4 on 2025-10-27 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тестовый чат',
                'verbose_name_plural': 'Тестовые чаты',
            },
        ),
        migrations.CreateModel(
            name='InputChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('CUSTOMER', 'Клиент'), ('MANAGER', 'Менеджер')], max_length=31, verbose_name='Автор')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image_url', models.TextField(blank=True, verbose_name='URL изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandbox_chats.inputchat', verbose_name='Чат')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
