# Generated by Django 5.0.4 on 2025-10-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputchat',
            name='answer_requirements',
            field=models.TextField(blank=True, verbose_name='Требования к ответу'),
        ),
    ]
