# Generated by Django 5.0.4 on 2025-10-28 11:36

import django.db.models.deletion
import utils.miscellaneous
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_chats', '0002_inputchat_answer_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxInputChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_requirements', models.TextField(blank=True, verbose_name='Требования к ответу')),
                ('created_at', models.DateTimeField(default=utils.miscellaneous.datetime_now_msk, verbose_name='Создано')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тестовый чат',
                'verbose_name_plural': 'Тестовые чаты',
            },
        ),
        migrations.CreateModel(
            name='SandboxSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Создано'), ('IN PROGRESS', 'Выполняется'), ('INTERRUPTED', 'Прервано'), ('FINISHED', 'Завершено')], default='CREATED', max_length=31, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=utils.miscellaneous.datetime_now_msk, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Тестовая сессия',
                'verbose_name_plural': 'Тестовые сессии',
            },
        ),
        migrations.RemoveField(
            model_name='inputchatmessage',
            name='chat',
        ),
        migrations.CreateModel(
            name='SandboxOutputChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_requirements', models.TextField(blank=True, verbose_name='Требования к ответу')),
                ('created_at', models.DateTimeField(default=utils.miscellaneous.datetime_now_msk, verbose_name='Создано')),
                ('avg_rate', models.FloatField(default=None, null=True, verbose_name='Средняя оценка')),
                ('min_rate', models.SmallIntegerField(default=None, null=True, verbose_name='Минимальная оценка')),
                ('max_rate', models.SmallIntegerField(default=None, null=True, verbose_name='Максимальная оценка')),
                ('input_chat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox_chats.sandboxinputchat', verbose_name='Основано на чате')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandbox_chats.sandboxsession', verbose_name='Тестовая сессия')),
            ],
            options={
                'verbose_name': 'Выходной тестовый чат',
                'verbose_name_plural': 'Выходные тестовые чаты',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('CUSTOMER', 'Клиент'), ('MANAGER', 'Менеджер')], max_length=31, verbose_name='Автор')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image_url', models.TextField(blank=True, verbose_name='URL изображения')),
                ('created_at', models.DateTimeField(default=utils.miscellaneous.datetime_now_msk, verbose_name='Создано')),
                ('input_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandbox_chats.sandboxinputchat', verbose_name='Входной чат')),
                ('output_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandbox_chats.sandboxoutputchat', verbose_name='Выходной чат')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='SandboxSessionInputChatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandbox_chats.sandboxinputchat', verbose_name='Тестовый чат')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandbox_chats.sandboxsession', verbose_name='Тестовая сессия')),
            ],
            options={
                'verbose_name': 'Связь Тестовая сессия - Тестовый чат',
                'verbose_name_plural': 'Связи Тестовая сессия - Тестовый чат',
            },
        ),
        migrations.CreateModel(
            name='SandboxTextAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(verbose_name='Оценка')),
                ('rate_explanation', models.TextField(verbose_name='Пояснение к оценке')),
                ('text', models.TextField(verbose_name='Текст')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandbox_chats.sandboxoutputchat', verbose_name='Тестовый чат')),
            ],
            options={
                'verbose_name': 'Ответы на тесты',
                'abstract': False,
            },
        ),
    ]
