# Generated by Django 5.0.4 on 2025-10-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0029_alter_amochatbotsandboxinputchatlink_chat_and_more'),
        ('sandbox_chats', '0003_sandboxinputchat_sandboxsession_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InputChat',
        ),
        migrations.DeleteModel(
            name='InputChatMessage',
        ),
    ]
