# Generated by Django 5.0.4 on 2025-10-28 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_chats', '0004_delete_inputchat_delete_inputchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='input_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox_chats.sandboxinputchat', verbose_name='Входной чат'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='output_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox_chats.sandboxoutputchat', verbose_name='Выходной чат'),
        ),
    ]
