# Generated by Django 5.0.4 on 2025-03-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=255, verbose_name='Идентификатор объекта')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING_DATA', 'Preparing Data'), ('ANSWER_GENERATION', 'Answer Generation'), ('ANSWER_SENDING', 'Answer Sending'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled'), ('INTERRUPTED', 'Interrupted')], db_index=True, default='PENDING', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задача чат-бота',
                'verbose_name_plural': 'Задачи чат-ботов',
            },
        ),
    ]
