# Generated by Django 5.0.4 on 2025-05-29 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amo', '0012_alter_handleblenote_options_amoorigin_account_and_more'),
        ('avito_account', '0010_avitoaccount_balance_alerting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoContactAvitoChatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.BigIntegerField(db_index=True, verbose_name='Идентификатор контакта в системе амо')),
                ('chat_id', models.CharField(db_index=True, max_length=255, verbose_name='Идентфикатор чата в системе Авито')),
                ('amo_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amoaccount', verbose_name='Амо-аккаунт')),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avito_account.avitoaccount', verbose_name='Авито-аккаунт')),
            ],
            options={
                'verbose_name': 'Связь Амо-Контакт - Авито-Чат',
                'verbose_name_plural': 'Связи Амо-Контакт - Авито-Чат',
                'unique_together': {('amo_account', 'contact_id'), ('avito_account', 'chat_id')},
            },
        ),
    ]
