# Generated by Django 5.0.4 on 2025-05-30 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0013_remove_amoorigin_code_alter_amochatbottask_talk_id'),
        ('amo_a5client', '0001_initial'),
        ('avito_account', '0010_avitoaccount_balance_alerting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoAvitoAccountsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('amo_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amo.amoaccount', verbose_name='Амо-аккаунт')),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avito_account.avitoaccount', unique=True, verbose_name='Авито-аккаунт')),
            ],
            options={
                'verbose_name': 'Связь аккаунтов Амо-Авито',
                'verbose_name_plural': 'Связи аккаунтов Амо-Авито',
            },
        ),
    ]
