# Generated by Django 5.0.4 on 2025-06-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo_a5client', '0002_amoavitoaccountslink'),
        ('avito_account', '0010_avitoaccount_balance_alerting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amoavitoaccountslink',
            name='avito_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='avito_account.avitoaccount', verbose_name='Авито-аккаунт'),
        ),
    ]
