# Generated by Django 5.0.4 on 2025-06-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo_a5client', '0003_alter_amoavitoaccountslink_avito_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_created_at', models.IntegerField(db_index=True)),
                ('text', models.TextField()),
                ('author_name', models.TextField()),
                ('amo_account_id', models.IntegerField()),
                ('contact_id', models.IntegerField()),
            ],
        ),
    ]
