# Generated by Django 5.0.4 on 2025-07-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo_a5client', '0004_messagecontactlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontactlink',
            name='avito_account_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagecontactlink',
            name='avito_chat_id',
            field=models.CharField(default=None, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='messagecontactlink',
            name='avito_message_id',
            field=models.CharField(default=None, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='messagecontactlink',
            name='contact_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='AmoContactAvitoChatLink',
        ),
    ]
