# Generated by Django 5.0.4 on 2025-07-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo_a5client', '0005_messagecontactlink_avito_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecontactlink',
            name='avito_account_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
