# Generated by Django 5.0.4 on 2024-11-05 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avito_account', '0009_sendingcampaign_auto_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активирован')),
                ('total_info', models.TextField(verbose_name='Общая информация')),
                ('rules', models.TextField(verbose_name='Правила при общении')),
                ('checkpoints', models.TextField(verbose_name='Шаги при общении')),
                ('avito_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_bots', to='avito_account.avitoaccount', verbose_name='ИИ чат бот')),
            ],
            options={
                'verbose_name': 'ИИ чат бот',
                'verbose_name_plural': 'ИИ чат боты',
            },
        ),
    ]
