# Generated by Django 5.0.4 on 2024-11-11 07:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0009_sendingcampaign_auto_generated_and_more'),
        ('chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatbot',
            name='waiting_minutes',
            field=models.PositiveSmallIntegerField(default=1, help_text='Укажите количество минут от 1 до 120', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Ожидание ответа от менеджера(минуты)'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChatBotTask',
            fields=[
                ('chat_id', models.CharField()),
                ('message_id', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
                ('tokens_completion', models.IntegerField(default=0, verbose_name='Токены на вычисления')),
                ('tokens_prompt', models.IntegerField(default=0, verbose_name='Токены на контекст')),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito_account.avitoaccount')),
            ],
            options={
                'verbose_name': 'Ответ чат бота',
                'verbose_name_plural': 'Ответы чат бота',
            },
        ),
    ]
