# Generated by Django 5.0.4 on 2024-11-07 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatbot',
            name='waiting_minutes',
            field=models.PositiveSmallIntegerField(default=1, help_text='Укажите количество минут от 1 до 120', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Ожидание ответа от менеджера(минуты)'),
            preserve_default=False,
        ),
    ]
