# Generated by Django 5.0.4 on 2024-11-12 07:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0002_aichatbot_waiting_minutes_chatbottask'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatbot',
            name='work_time_from',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Начало работы МСК (Пн-Вс)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aichatbot',
            name='work_time_to',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Окончание работы МСК (Пн-Вс)'),
            preserve_default=False,
        ),
    ]
