# Generated by Django 5.0.4 on 2024-11-09 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0009_sendingcampaign_auto_generated_and_more'),
        ('chat_bot', '0002_aichatbot_waiting_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotAnswer',
            fields=[
                ('chat_id', models.TextField()),
                ('message_id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('actual', models.BooleanField(default=True)),
                ('answer_text', models.TextField(verbose_name='Текст ответа')),
                ('tokens_completion', models.IntegerField(default=0, verbose_name='Токены на вычисления')),
                ('tokens_prompt', models.IntegerField(default=0, verbose_name='Токены на контекст')),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito_account.avitoaccount')),
            ],
            options={
                'verbose_name': 'Ответ чат бота',
                'verbose_name_plural': 'Ответы чат бота',
            },
        ),
    ]
