# Generated by Django 5.0.4 on 2024-11-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0003_aichatbot_work_time_from_aichatbot_work_time_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatbot',
            name='target_action',
            field=models.TextField(default='Взять номер телефона клиента для связи', verbose_name='Целевое действие'),
        ),
        migrations.AddField(
            model_name='chatbottask',
            name='target_action_success',
            field=models.BooleanField(default=False, verbose_name='Целевое действие достигнуто'),
        ),
    ]
