# Generated by Django 5.0.4 on 2024-11-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0003_aichatbot_work_time_from_aichatbot_work_time_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatbot',
            name='target_action',
            field=models.TextField(default='Взять номер телефона клиента для связи', verbose_name='Целевое действие'),
        ),
        migrations.AddField(
            model_name='chatbottask',
            name='address',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Адрес клиента'),
        ),
        migrations.AddField(
            model_name='chatbottask',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='Емайл'),
        ),
        migrations.AddField(
            model_name='chatbottask',
            name='mobile',
            field=models.TextField(blank=True, null=True, verbose_name='Мобильный номер'),
        ),
        migrations.AddField(
            model_name='chatbottask',
            name='telegram',
            field=models.TextField(blank=True, null=True, verbose_name='Телеграм'),
        ),
        migrations.AddField(
            model_name='chatbottask',
            name='whatsapp',
            field=models.TextField(blank=True, null=True, verbose_name='Вацап'),
        ),
    ]
