# Generated by Django 5.0.4 on 2024-11-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0003_chatbotanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotanswer',
            name='chat_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='chatbotanswer',
            name='message_id',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
    ]
