# Generated by Django 5.0.4 on 2024-11-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0009_sendingcampaign_auto_generated_and_more'),
        ('chat_bot', '0004_alter_chatbotanswer_chat_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatBotAnswer',
            new_name='ChatBotTask',
        ),
    ]
