# Generated by Django 5.0.4 on 2024-11-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0004_aichatbot_target_action_chatbottask_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbottask',
            name='email',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Емайл'),
        ),
        migrations.AlterField(
            model_name='chatbottask',
            name='mobile',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Мобильный номер'),
        ),
        migrations.AlterField(
            model_name='chatbottask',
            name='telegram',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='chatbottask',
            name='whatsapp',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Вацап'),
        ),
    ]
