# Generated by Django 5.0.4 on 2024-12-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0005_alter_chatbottask_email_alter_chatbottask_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatbot',
            name='shutdown_after_manager',
            field=models.BooleanField(default=False, verbose_name='Выключаться после менеджера'),
        ),
    ]
