# Generated by Django 5.0.4 on 2024-11-09 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0005_rename_chatbotanswer_chatbottask'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbottask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
