# Generated by Django 5.0.4 on 2024-11-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0006_chatbottask_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbottask',
            name='actual',
        ),
        migrations.AlterField(
            model_name='chatbottask',
            name='answer_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ответа'),
        ),
    ]
