# Generated by Django 5.0.4 on 2024-12-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0006_aichatbot_shutdown_after_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbottask',
            name='chat_shutdown_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
