# Generated by Django 5.0.4 on 2025-01-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0007_chatbottask_chat_shutdown_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbottask',
            name='summary_sanded',
            field=models.BooleanField(default=False, verbose_name='Сводка была отправлена'),
        ),
    ]
