# Generated by Django 5.0.4 on 2025-01-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0008_chatbottask_summary_sanded'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbottask',
            name='daily_statistics_report',
            field=models.BooleanField(default=False, verbose_name='Отчёт с ежедневной статистикой'),
        ),
        migrations.AddField(
            model_name='chatbottask',
            name='history_for_daily_statistics',
            field=models.BooleanField(default=False, verbose_name='История чатов для статистики'),
        ),
    ]
