# Generated by Django 5.0.4 on 2025-02-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0009_aichatbot_histories_for_statistics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichatbot',
            name='histories_for_statistics',
        ),
        migrations.AddField(
            model_name='aichatbot',
            name='histories_closed',
            field=models.BooleanField(default=False, verbose_name='История дожатых клиентов'),
        ),
        migrations.AddField(
            model_name='aichatbot',
            name='histories_open',
            field=models.BooleanField(default=False, verbose_name='История НЕдожатых клиентов'),
        ),
    ]
