# Generated by Django 5.0.4 on 2025-02-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0010_remove_aichatbot_histories_for_statistics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbottask',
            name='is_incoming',
            field=models.BooleanField(default=True, verbose_name='Входящее сообщение'),
        ),
    ]
