# Generated by Django 5.0.4 on 2025-04-25 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0010_avitoaccount_balance_alerting'),
        ('chat_bot', '0011_chatbottask_is_incoming'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Населенный пункт')),
                ('location_slug', models.CharField(db_index=True, max_length=255, verbose_name='Код населенного пункта')),
                ('telegram_id', models.CharField(max_length=31, verbose_name='telegram id')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avito_account.avitoaccount', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.AddField(
            model_name='chatbottask',
            name='company_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat_bot.companybranch'),
        ),
    ]
