# Generated by Django 5.0.4 on 2025-05-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0012_companybranch_chatbottask_company_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatbot',
            name='prompt_example',
            field=models.TextField(blank=True, verbose_name='Пример промпта'),
        ),
    ]
