# Generated by Django 5.0.4 on 2025-05-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0013_aichatbot_prompt_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatbot',
            name='read_only',
            field=models.BooleanField(default=False, verbose_name='Только читает сообщения'),
        ),
    ]
