# Generated by Django 5.0.4 on 2025-05-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0014_aichatbot_read_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatbot',
            name='send_new_contact_report',
            field=models.BooleanField(default=True, verbose_name='Отправлять отчет о новом контакте'),
        ),
    ]
