# Generated by Django 5.0.4 on 2025-05-12 17:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0010_avitoaccount_balance_alerting'),
        ('chat_bot', '0015_aichatbot_send_new_contact_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatbot',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avito_account.avitoaccount', verbose_name='Авито-аккаунт'),
        ),
        migrations.AddField(
            model_name='aichatbot',
            name='description',
            field=models.TextField(blank=True, verbose_name='Для каких тем используется'),
        ),
        migrations.AddField(
            model_name='aichatbot',
            name='name',
            field=models.CharField(db_index=True, default='Безымянный ИИ', max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='aichatbot',
            name='waiting_seconds',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ожидание ответа от менеджера (секунды)'),
        ),
        migrations.AlterField(
            model_name='aichatbot',
            name='checkpoints',
            field=models.TextField(blank=True, verbose_name='Шаги при общении'),
        ),
        migrations.AlterField(
            model_name='aichatbot',
            name='rules',
            field=models.TextField(blank=True, verbose_name='Правила при общении'),
        ),
        migrations.AlterField(
            model_name='aichatbot',
            name='target_action',
            field=models.TextField(blank=True, default='Взять номер телефона клиента для связи', verbose_name='Целевое действие'),
        ),
        migrations.AlterField(
            model_name='aichatbot',
            name='total_info',
            field=models.TextField(blank=True, verbose_name='Общая информация'),
        ),
    ]
