# Generated by Django 5.0.4 on 2025-05-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0016_aichatbot_account_aichatbot_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichatbot',
            name='avito_account',
        ),
        migrations.RemoveField(
            model_name='aichatbot',
            name='waiting_minutes',
        ),
    ]
