# Generated by Django 5.0.4 on 2025-05-13 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0010_avitoaccount_balance_alerting'),
        ('chat_bot', '0017_remove_aichatbot_avito_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichatbot',
            name='prompt_example',
        ),
        migrations.AlterField(
            model_name='aichatbot',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='avito_account.avitoaccount', verbose_name='Авито-аккаунт'),
        ),
        migrations.CreateModel(
            name='AvitoPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Промпт')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot.aichatbot', verbose_name='Чат-бот')),
            ],
            options={
                'verbose_name': 'Промпт',
                'verbose_name_plural': 'Промпты',
                'unique_together': {('chatbot', 'title')},
            },
        ),
    ]
