# Generated by Django 5.0.4 on 2025-05-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0018_remove_aichatbot_prompt_example_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichatbot',
            name='checkpoints',
        ),
        migrations.RemoveField(
            model_name='aichatbot',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aichatbot',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='aichatbot',
            name='target_action',
        ),
        migrations.RemoveField(
            model_name='aichatbot',
            name='total_info',
        ),
    ]
