# Generated by Django 5.0.4 on 2025-07-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0011_sendingreport_avito_account_name'),
        ('chat_bot', '0019_remove_aichatbot_checkpoints_and_more'),
        ('transcriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=63, verbose_name='Идентификатор чата')),
                ('message_id', models.CharField(db_index=True, max_length=63, verbose_name='Идентификатор сообщения')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito_account.avitoaccount', verbose_name='Авито-аккаунт')),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcriptions.transcription', verbose_name='Транскрипция')),
            ],
        ),
    ]
