# Generated by Django 5.0.4 on 2025-08-05 07:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_account', '0011_sendingreport_avito_account_name'),
        ('chat_bot', '0020_avitotranscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatbot',
            name='delay_before_launch_trigger_sec',
            field=models.PositiveIntegerField(default=600, verbose_name='Задержка перед запуском триггера'),
        ),
        migrations.AddField(
            model_name='chatbottask',
            name='message_created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 7, 38, 36, 340725, tzinfo=datetime.timezone.utc), verbose_name='Когда создано сообщение'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DialogTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_before_launch_trigger_sec', models.PositiveIntegerField(default=600, verbose_name='Задержка перед запуском триггера')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('only_when_client_is_silent', models.BooleanField(default=True, verbose_name='Только когда клиент не отвечает')),
                ('additional_condition', models.TextField(blank=True, verbose_name='Дополнительное условие')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot.aichatbot', verbose_name='Чат-бот')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat_bot.dialogtrigger', verbose_name='Вызывает триггер')),
            ],
            options={
                'verbose_name': 'Триггер',
                'verbose_name_plural': 'Триггеры',
            },
        ),
        migrations.AddField(
            model_name='aichatbot',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat_bot.dialogtrigger', verbose_name='Вызывает триггер'),
        ),
        migrations.CreateModel(
            name='WorkedTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=255, verbose_name='Идентификатор чата в системе Авито')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создан')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito_account.avitoaccount', verbose_name='Аккаунт')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot.dialogtrigger', verbose_name='Триггер')),
            ],
        ),
    ]
