# Generated by Django 5.0.4 on 2025-08-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0021_aichatbot_delay_before_launch_trigger_sec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatbot',
            name='delay_before_launch_trigger_sec',
            field=models.PositiveIntegerField(default=600, verbose_name='Запускать следующий триггер через (сек)'),
        ),
        migrations.AlterField(
            model_name='dialogtrigger',
            name='delay_before_launch_trigger_sec',
            field=models.PositiveIntegerField(default=600, verbose_name='Запускать следующий триггер через (сек)'),
        ),
    ]
