# Generated by Django 5.0.4 on 2025-10-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0022_alter_aichatbot_delay_before_launch_trigger_sec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbottask',
            name='answered_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Когда отвечено'),
        ),
    ]
