# Generated by Django 5.0.4 on 2026-06-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0023_chatbottask_answered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbottask',
            name='cancel_reason',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='chatbottask',
            name='status',
            field=models.CharField(db_index=True, default=None, max_length=15, null=True, verbose_name='Статус'),
        ),
    ]
