# Generated by Django 5.0.4 on 2026-06-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0024_chatbottask_cancel_reason_chatbottask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbottask',
            name='status',
            field=models.CharField(db_index=True, default=None, max_length=31, null=True, verbose_name='Статус'),
        ),
    ]
