item_list = {'meta': {'page': 1, 'per_page': 100},
             'resources': [{'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3755530203,
                            'status': 'active',
                            'title': 'Осп osb плита продажа 6 мм 9 мм',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/osp_osb_plita_prodazha_6_mm_9_mm_3755530203'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3755402557,
                            'status': 'active',
                            'title': 'Штукатурка knauf mp75',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/shtukaturka_knauf_mp75_3755402557'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3755402240,
                            'status': 'old',
                            'title': 'Утеплитель isover',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/uteplitel_isover_3755402240'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3755108450,
                            'status': 'active',
                            'title': 'Аквапанель aquapanel',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/akvapanel_aquapanel_3755108450'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3755005465,
                            'status': 'active',
                            'title': 'Профнастил',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/profnastil_3755005465'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3754958906,
                            'status': 'active',
                            'title': 'Пеноплекс технониколь',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/penopleks_tehnonikol_3754958906'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3754919232,
                            'status': 'active',
                            'title': 'Утеплитель knauf кнауф',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/uteplitel_knauf_knauf_3754919232'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3754705166,
                            'status': 'active',
                            'title': 'Роквул акустик',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/rokvul_akustik_3754705166'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3754632909,
                            'status': 'active',
                            'title': 'Утеплитель ursa',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/uteplitel_ursa_3754632909'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3723611997,
                            'status': 'old',
                            'title': 'Утеплитель пеноплекс. Пеноплекс',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/uteplitel_penopleks._penopleks_3723611997'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3723565374,
                            'status': 'active',
                            'title': 'Кольцо жби кольца. Доставка жби колец',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/koltso_zhbi_koltsa._dostavka_zhbi_kolets_3723565374'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3723520854,
                            'status': 'old',
                            'title': 'Бордюры и поребрики',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/bordyury_i_porebriki_3723520854'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3723424127,
                            'status': 'active',
                            'title': 'Тротуарная плитка',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/trotuarnaya_plitka_3723424127'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3723419862,
                            'status': 'old',
                            'title': 'Металлопрокат розница',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/metalloprokat_roznitsa_3723419862'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3723371485,
                            'status': 'active',
                            'title': 'Профнастил Профлист',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/profnastil_proflist_3723371485'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3723273489,
                            'status': 'old',
                            'title': 'Кирпич. Доставка кирпичей. Кирпичи любых видов',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/kirpich._dostavka_kirpichey._kirpichi_lyubyh_vidov_3723273489'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3722990347,
                            'status': 'old',
                            'title': 'Сухие строительные смеси. Стройматериалы',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/suhie_stroitelnye_smesi._stroymaterialy_3722990347'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3722822084,
                            'status': 'old',
                            'title': 'Плиты перекрытия жби',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/plity_perekrytiya_zhbi_3722822084'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3722711266,
                            'status': 'old',
                            'title': 'Утеплитель минераловатный',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/uteplitel_mineralovatnyy_3722711266'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3722704038,
                            'status': 'active',
                            'title': 'Перемычки железобетонные. жби перемычки',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/peremychki_zhelezobetonnye._zhbi_peremychki_3722704038'},
                           {'address': 'Республика Татарстан, Казань, ул. Сибирский Тракт, '
                                       '34к12',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 3722666047,
                            'price': 0,
                            'status': 'active',
                            'title': 'Гипсокартон кнауф. knauf гипсокартон',
                            'url': 'https://www.avito.ru/kazan/remont_i_stroitelstvo/gipsokarton_knauf._knauf_gipsokarton_3722666047'},
                           {'address': 'Республика Татарстан, Казань, ул. Баумана',
                            'category': {'id': 21, 'name': 'Бытовая техника'},
                            'id': 2379636016,
                            'price': 2700,
                            'status': 'old',
                            'title': 'Сушилка для овощей и фруктов',
                            'url': 'https://www.avito.ru/kazan/bytovaya_tehnika/sushilka_dlya_ovoschey_i_fruktov_2379636016'},
                           {'address': 'Ярославская обл., Тутаевский р-н, Артемьевское '
                                       'сельское поселение',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 2155837725,
                            'price': 2500,
                            'status': 'old',
                            'title': 'Насосная станция новая свд- 160/1,5 Калибр',
                            'url': 'https://www.avito.ru/tutaev/remont_i_stroitelstvo/nasosnaya_stantsiya_novaya_svd-_16015_kalibr_2155837725'},
                           {'address': 'Ярославская обл., Тутаевский р-н, Артемьевское '
                                       'сельское поселение',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 2155641416,
                            'price': 20000,
                            'status': 'old',
                            'title': 'Компрессор воздушный бу 380',
                            'url': 'https://www.avito.ru/tutaev/remont_i_stroitelstvo/kompressor_vozdushnyy_bu_380_2155641416'},
                           {'address': 'Ярославская обл., Тутаевский р-н, Артемьевское '
                                       'сельское поселение',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 2155452857,
                            'price': 15000,
                            'status': 'old',
                            'title': 'Отбойный молоток Dewalt D 25902',
                            'url': 'https://www.avito.ru/tutaev/remont_i_stroitelstvo/otboynyy_molotok_dewalt_d_25902_2155452857'},
                           {'address': 'Ярославская обл., Тутаевский р-н, Артемьевское '
                                       'сельское поселение',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 2155274292,
                            'price': 10000,
                            'status': 'old',
                            'title': 'Отбойный молоток Makita',
                            'url': 'https://www.avito.ru/tutaev/remont_i_stroitelstvo/otboynyy_molotok_makita_2155274292'},
                           {'address': 'Ярославская обл., Тутаевский р-н, Артемьевское '
                                       'сельское поселение',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 2155046691,
                            'price': 15000,
                            'status': 'old',
                            'title': 'Генератор бензиновый бу (Sturm PG8719 WN)',
                            'url': 'https://www.avito.ru/tutaev/remont_i_stroitelstvo/generator_benzinovyy_bu_sturm_pg8719_wn_2155046691'},
                           {'address': 'Ярославская обл., Тутаевский р-н, д. Емишево',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 2123615532,
                            'price': 55000,
                            'status': 'old',
                            'title': 'Кран по типу пионер',
                            'url': 'https://www.avito.ru/tutaev/remont_i_stroitelstvo/kran_po_tipu_pioner_2123615532'},
                           {'address': 'Ярославская обл., Тутаевский р-н, д. Емишево',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 2123609763,
                            'price': 7000,
                            'status': 'old',
                            'title': 'Смеситель для бетона и раствора',
                            'url': 'https://www.avito.ru/tutaev/remont_i_stroitelstvo/smesitel_dlya_betona_i_rastvora_2123609763'},
                           {'address': 'Ярославская обл., Тутаевский р-н, д. Емишево',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 2123406538,
                            'price': 80000,
                            'status': 'old',
                            'title': 'Оборудование для промышленных бетонных полов',
                            'url': 'https://www.avito.ru/tutaev/remont_i_stroitelstvo/oborudovanie_dlya_promyshlennyh_betonnyh_polov_2123406538'},
                           {'address': 'Ярославская обл., Тутаевский р-н, д. Емишево',
                            'category': {'id': 19, 'name': 'Ремонт и строительство'},
                            'id': 1738999975,
                            'price': 25000,
                            'status': 'old',
                            'title': 'Мозаично-шлифовальная машина',
                            'url': 'https://www.avito.ru/tutaev/remont_i_stroitelstvo/mozaichno-shlifovalnaya_mashina_1738999975'}]}
