statistic_response =  {'itemId': 1824412051,
                       'stats': [{'date': '2021-01-01',
                                  'uniqContacts': 9,
                                  'uniqFavorites': 0,
                                  'uniqViews': 56},
                                 {'date': '2021-02-01',
                                  'uniqContacts': 12,
                                  'uniqFavorites': 0,
                                  'uniqViews': 75},
                                 {'date': '2021-03-01',
                                  'uniqContacts': 16,
                                  'uniqFavorites': 0,
                                  'uniqViews': 57},
                                 {'date': '2021-04-01',
                                  'uniqContacts': 7,
                                  'uniqFavorites': 0,
                                  'uniqViews': 19}]},
                      {'itemId': 1824729971, 'stats': []},
                      {'itemId': 1887954225, 'stats': []},
                      {'itemId': 1888003780,
                       'stats': [{'date': '2021-05-01',
                                  'uniqContacts': 0,
                                  'uniqFavorites': 0,
                                  'uniqViews': 0}]},
                      {'itemId': 1888644892, 'stats': []},
                      {'itemId': 1920860529, 'stats': []},
                      {'itemId': 1952025051, 'stats': []},
                      {'itemId': 1952576254, 'stats': []},
                      {'itemId': 1952664590,
                       'stats': [{'date': '2021-03-01',
                                  'uniqContacts': 37,
                                  'uniqFavorites': 0,
                                  'uniqViews': 132},
                                 {'date': '2021-04-01',
                                  'uniqContacts': 15,
                                  'uniqFavorites': 0,
                                  'uniqViews': 53},
                                 {'date': '2021-05-01',
                                  'uniqContacts': 8,
                                  'uniqFavorites': 0,
                                  'uniqViews': 35},
                                 {'date': '2021-07-01',
                                  'uniqContacts': 0,
                                  'uniqFavorites': 0,
                                  'uniqViews': 1},
                                 {'date': '2021-08-01',
                                  'uniqContacts': 0,
                                  'uniqFavorites': 0,
                                  'uniqViews': 1}]},
                      {'itemId': 1952831619, 'stats': []},
                      {'itemId': 2048189961,
                       'stats': [{'date': '2021-01-01',
                                  'uniqContacts': 1,
                                  'uniqFavorites': 0,
                                  'uniqViews': 7},
                                 {'date': '2021-06-01',
                                  'uniqContacts': 0,
                                  'uniqFavorites': 0,
                                  'uniqViews': 1}]},
                      {'itemId': 2048810709,
                       'stats': [{'date': '2021-01-01',
                                  'uniqContacts': 1,
                                  'uniqFavorites': 0,
                                  'uniqViews': 89},
                                 {'date': '2021-02-01',
                                  'uniqContacts': 0,
                                  'uniqFavorites': 0,
                                  'uniqViews': 3}]},
                      {'itemId': 2112668974,
                       'stats': [{'date': '2021-03-01',
                                  'uniqContacts': 2,
                                  'uniqFavorites': 0,
                                  'uniqViews': 21},
                                 {'date': '2021-04-01',
                                  'uniqContacts': 9,
                                  'uniqFavorites': 0,
                                  'uniqViews': 43},
                                 {'date': '2021-05-01',
                                  'uniqContacts': 1,
                                  'uniqFavorites': 0,
                                  'uniqViews': 11},
                                 {'date': '2021-06-01',
                                  'uniqContacts': 3,
                                  'uniqFavorites': 0,
                                  'uniqViews': 5}]},
                      {'itemId': 2176112011,
                       'stats': [{'date': '2021-07-01',
                                  'uniqContacts': 50,
                                  'uniqFavorites': 0,
                                  'uniqViews': 188}]},
                      {'itemId': 2176151523,
                       'stats': [{'date': '2021-07-01',
                                  'uniqContacts': 26,
                                  'uniqFavorites': 0,
                                  'uniqViews': 80},
                                 {'date': '2021-08-01',
                                  'uniqContacts': 3,
                                  'uniqFavorites': 0,
                                  'uniqViews': 4}]},
                      {'itemId': 2176446301,
                       'stats': [{'date': '2021-07-01',
                                  'uniqContacts': 20,
                                  'uniqFavorites': 0,
                                  'uniqViews': 112},
                                 {'date': '2021-08-01',
                                  'uniqContacts': 1,
                                  'uniqFavorites': 0,
                                  'uniqViews': 4}]},
                      {'itemId': 2208372750, 'stats': []},
                      {'itemId': 2208433685, 'stats': []},
                      {'itemId': 2208523415, 'stats': []},
                      {'itemId': 2208607530, 'stats': []},
                      {'itemId': 2208666086, 'stats': []},
                      {'itemId': 2208797744, 'stats': []},
                      {'itemId': 2240148876, 'stats': []},
                      {'itemId': 2240567882, 'stats': []},
                      {'itemId': 2272198253, 'stats': []},
                      {'itemId': 2272373640, 'stats': []},
                      {'itemId': 2272507689, 'stats': []},
                      {'itemId': 2272588271, 'stats': []},
                      {'itemId': 2272823863, 'stats': []},
                      {'itemId': 2304051863, 'stats': []},
                      {'itemId': 2304062617, 'stats': []},
                      {'itemId': 2304644735, 'stats': []},
                      {'itemId': 2304738048, 'stats': []},
                      {'itemId': 2336359791, 'stats': []},
                      {'itemId': 2431987707, 'stats': []},
                      {'itemId': 2432349244, 'stats': []},
                      {'itemId': 2432467681, 'stats': []},
                      {'itemId': 2432570826, 'stats': []},
                      {'itemId': 2432730161, 'stats': []},
                      {'itemId': 2432839440, 'stats': []},
                      {'itemId': 2464582630, 'stats': []},
                      {'itemId': 2624306309, 'stats': []},
                      {'itemId': 3359934271, 'stats': []},
                      {'itemId': 3456191202, 'stats': []}]}}
